export const CourtsData = [
  // ------------------- Basketball -------------------
 {
    name: "Kaloor International Basketball Court",
    sportType: "Basketball",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "28x15 m",
    playerCount: 10,
    courtType: "Indoor, Hardwood",
    bookingCharge: 500,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/basketball1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Basketballs", "Scoreboard"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Great court!", "Well-maintained!"],
    owner: { name: "John Doe", phone: "1234567890", email: "john@example.com" },
    maxBookingHours: 2
  },
  {
    name: "MG Road Basketball Arena",
    sportType: "Basketball",
    location: "MG Road, Kochi",
    latitude: 9.9800,
    longitude: 76.2990,
    map: "https://www.google.com/maps?q=9.9800,76.2990&output=embed",
    size: "28x15 m",
    playerCount: 10,
    courtType: "Indoor, Wooden Floor",
    bookingCharge: 450,
    lighting: "Yes, LED Floodlights",
    photos: ["https://example.com/photos/basketball2.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Basketballs", "Scoreboard", "Hoops"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true }
    ],
    rating: 4.3,
    reviews: ["Indoor court, clean!", "Good lighting and floor"],
    owner: { name: "Anjali Menon", phone: "9876543210", email: "anjali@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Basketball Ground",
    sportType: "Basketball",
    location: "Fort Kochi, Kochi",
    latitude: 9.9650,
    longitude: 76.2420,
    map: "https://www.google.com/maps?q=9.9650,76.2420&output=embed",
    size: "28x15 m",
    playerCount: 10,
    courtType: "Outdoor, Concrete",
    bookingCharge: 400,
    lighting: "No",
    photos: ["https://example.com/photos/basketball3.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Basketballs", "Hoops"],
    slots: [
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false }
    ],
    rating: 4.0,
    reviews: ["Outdoor court, a bit rough floor", "Good for practice"],
    owner: { name: "Ravi Kumar", phone: "9012345678", email: "ravi@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Sports Complex",
    sportType: "Basketball",
    location: "Ernakulam, Kochi",
    latitude: 9.9810,
    longitude: 76.2995,
    map: "https://www.google.com/maps?q=9.9810,76.2995&output=embed",
    size: "28x15 m",
    playerCount: 10,
    courtType: "Indoor, Hardwood",
    bookingCharge: 550,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/basketball4.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Basketballs", "Scoreboard", "Hoops"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true }
    ],
    rating: 4.6,
    reviews: ["Very clean", "Indoor court with good lighting"],
    owner: { name: "Sana Thomas", phone: "9988776655", email: "sana@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vytilla Basketball Arena",
    sportType: "Basketball",
    location: "Vytilla, Kochi",
    latitude: 9.9750,
    longitude: 76.2990,
    map: "https://www.google.com/maps?q=9.9750,76.2990&output=embed",
    size: "28x15 m",
    playerCount: 10,
    courtType: "Indoor, Hardwood",
    bookingCharge: 500,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/basketball5.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Basketballs", "Scoreboard", "Hoops"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.4,
    reviews: ["Spacious indoor court", "Well-maintained"],
    owner: { name: "Vijay Sharma", phone: "9123456789", email: "vijay@example.com" },
    maxBookingHours: 2
  },

  // ------------------- Tennis -------------------
 {
    name: "Kaloor International Tennis Court",
    sportType: "Tennis",
    location: "Kaloor, Kochi",
    latitude: 9.9985,
    longitude: 76.3075,
    map: "https://www.google.com/maps?q=9.9985,76.3075&output=embed",
    size: "23.77x10.97 m",
    playerCount: 4,
    courtType: "Outdoor, Hard",
    bookingCharge: 400,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/tennis1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Tennis Balls", "Rackets", "Nets"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Great court!", "Well-maintained!"],
    owner: { name: "John Doe", phone: "1234567890", email: "john@example.com" },
    maxBookingHours: 2
  },
  {
    name: "MG Road Tennis Arena",
    sportType: "Tennis",
    location: "MG Road, Kochi",
    latitude: 9.9805,
    longitude: 76.2995,
    map: "https://www.google.com/maps?q=9.9805,76.2995&output=embed",
    size: "23.77x10.97 m",
    playerCount: 4,
    courtType: "Indoor, Hard",
    bookingCharge: 450,
    lighting: "Yes, LED Floodlights",
    photos: ["https://example.com/photos/tennis2.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Tennis Balls", "Rackets", "Nets"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true }
    ],
    rating: 4.3,
    reviews: ["Indoor court, clean!", "Good lighting and floor"],
    owner: { name: "Anjali Menon", phone: "9876543210", email: "anjali@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Tennis Ground",
    sportType: "Tennis",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "23.77x10.97 m",
    playerCount: 4,
    courtType: "Outdoor, Clay",
    bookingCharge: 400,
    lighting: "No",
    photos: ["https://example.com/photos/tennis3.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Tennis Balls", "Rackets", "Nets"],
    slots: [
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false }
    ],
    rating: 4.0,
    reviews: ["Outdoor clay court", "Good for practice"],
    owner: { name: "Ravi Kumar", phone: "9012345678", email: "ravi@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Tennis Complex",
    sportType: "Tennis",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "23.77x10.97 m",
    playerCount: 4,
    courtType: "Indoor, Hard",
    bookingCharge: 500,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tennis4.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Tennis Balls", "Rackets", "Nets"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true }
    ],
    rating: 4.6,
    reviews: ["Indoor court, clean", "Great for practice"],
    owner: { name: "Sana Thomas", phone: "9988776655", email: "sana@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vytilla Tennis Arena",
    sportType: "Tennis",
    location: "Vytilla, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "23.77x10.97 m",
    playerCount: 4,
    courtType: "Indoor, Hard",
    bookingCharge: 450,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/tennis5.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Tennis Balls", "Rackets", "Nets"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.4,
    reviews: ["Spacious indoor court", "Well-maintained"],
    owner: { name: "Vijay Sharma", phone: "9123456789", email: "vijay@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Uptown Tennis Club",
    sportType: "Tennis",
    location: "Mavoor Road, Kozhikode",
    latitude: 11.2560,
    longitude: 75.7804,
    map: "https://www.google.com/maps?q=11.2560,75.7804&z=15&output=embed",
    size: "23.77x10.97 m",
    playerCount: 2,
    courtType: "Outdoor, Grass",
    bookingCharge: 370,
    lighting: "No",
    photos: ["https://example.com/photos/tennis5.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Rackets", "Balls"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true }
    ],
    rating: 4.5,
    reviews: ["Perfect for casual matches.", "Friendly staff."],
    owner: { name: "Karen Smith", phone: "3344556677", email: "karen@example.com" },
    maxBookingHours: 2
  },
// ------------------- Football -------------------
  {
    name: "Kaloor International Football Field",
    sportType: "Football",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "105x68 m",
    playerCount: 22,
    courtType: "Outdoor, Grass",
    bookingCharge: 1000,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/football1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Football", "Goals", "Corner Flags"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Perfect field!", "Well-maintained!"],
    owner: { name: "John Doe", phone: "1234567890", email: "john@example.com" },
    maxBookingHours: 2
  },
  {
    name: "MG Road Football Arena",
    sportType: "Football",
    location: "MG Road, Kochi",
    latitude: 9.9805,
    longitude: 76.2995,
    map: "https://www.google.com/maps?q=9.9805,76.2995&output=embed",
    size: "100x65 m",
    playerCount: 22,
    courtType: "Outdoor, Artificial Turf",
    bookingCharge: 1200,
    lighting: "Yes, LED Floodlights",
    photos: ["https://example.com/photos/football2.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Football", "Goals", "Corner Flags"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true }
    ],
    rating: 4.3,
    reviews: ["Good turf", "Well-lit for evening games"],
    owner: { name: "Anjali Menon", phone: "9876543210", email: "anjali@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Football Ground",
    sportType: "Football",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "105x68 m",
    playerCount: 22,
    courtType: "Outdoor, Grass",
    bookingCharge: 900,
    lighting: "No",
    photos: ["https://example.com/photos/football3.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Football", "Goals", "Corner Flags"],
    slots: [
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false }
    ],
    rating: 4.0,
    reviews: ["Spacious grass field", "Great for practice matches"],
    owner: { name: "Ravi Kumar", phone: "9012345678", email: "ravi@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Football Complex",
    sportType: "Football",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "100x65 m",
    playerCount: 22,
    courtType: "Outdoor, Artificial Turf",
    bookingCharge: 1100,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/football4.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Football", "Goals", "Corner Flags"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true }
    ],
    rating: 4.6,
    reviews: ["Perfect turf for matches", "Well-maintained field"],
    owner: { name: "Sana Thomas", phone: "9988776655", email: "sana@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vytilla Football Arena",
    sportType: "Football",
    location: "Vytilla, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "105x68 m",
    playerCount: 22,
    courtType: "Outdoor, Grass",
    bookingCharge: 1000,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/football5.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Football", "Goals", "Corner Flags"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.4,
    reviews: ["Good grass field", "Spacious and clean"],
    owner: { name: "Vijay Sharma", phone: "9123456789", email: "vijay@example.com" },
    maxBookingHours: 2
  },
// ------------------- Volleyball -------------------
  {
    name: "Kaloor International Volleyball Court",
    sportType: "Volleyball",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "18x9 m",
    playerCount: 12,
    courtType: "Indoor, Hardwood",
    bookingCharge: 500,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/volleyball1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Volleyball", "Net", "Scoreboard"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Great indoor court!", "Well-maintained!"],
    owner: { name: "John Doe", phone: "1234567890", email: "john@example.com" },
    maxBookingHours: 2
  },
  {
    name: "MG Road Volleyball Arena",
    sportType: "Volleyball",
    location: "MG Road, Kochi",
    latitude: 9.9805,
    longitude: 76.2995,
    map: "https://www.google.com/maps?q=9.9805,76.2995&output=embed",
    size: "18x9 m",
    playerCount: 12,
    courtType: "Indoor, Synthetic",
    bookingCharge: 600,
    lighting: "Yes, LED Floodlights",
    photos: ["https://example.com/photos/volleyball2.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Volleyball", "Net", "Scoreboard"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true }
    ],
    rating: 4.3,
    reviews: ["Good court", "Perfect for practice"],
    owner: { name: "Anjali Menon", phone: "9876543210", email: "anjali@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Volleyball Ground",
    sportType: "Volleyball",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "18x9 m",
    playerCount: 12,
    courtType: "Outdoor, Sand",
    bookingCharge: 400,
    lighting: "No",
    photos: ["https://example.com/photos/volleyball3.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Volleyball", "Net"],
    slots: [
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false }
    ],
    rating: 4.0,
    reviews: ["Nice sand court", "Great for beach volleyball practice"],
    owner: { name: "Ravi Kumar", phone: "9012345678", email: "ravi@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Volleyball Complex",
    sportType: "Volleyball",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "18x9 m",
    playerCount: 12,
    courtType: "Indoor, Hardwood",
    bookingCharge: 550,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/volleyball4.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Volleyball", "Net", "Scoreboard"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true }
    ],
    rating: 4.6,
    reviews: ["Perfect indoor court", "Well-maintained floor"],
    owner: { name: "Sana Thomas", phone: "9988776655", email: "sana@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vytilla Volleyball Arena",
    sportType: "Volleyball",
    location: "Vytilla, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "18x9 m",
    playerCount: 12,
    courtType: "Indoor, Synthetic",
    bookingCharge: 500,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/volleyball5.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Volleyball", "Net", "Scoreboard"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.4,
    reviews: ["Good indoor court", "Well-kept facilities"],
    owner: { name: "Vijay Sharma", phone: "9123456789", email: "vijay@example.com" },
    maxBookingHours: 2
  },

// ------------------- Badminton -------------------
  {
    name: "Kaloor International Badminton Court",
    sportType: "Badminton",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "13.4x6.1 m",
    playerCount: 4,
    courtType: "Indoor, Wooden",
    bookingCharge: 300,
    lighting: "Yes, LED Floodlights",
    photos: ["https://example.com/photos/badminton1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Shuttlecocks", "Rackets", "Scoreboard"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Excellent court!", "Clean and well-maintained"],
    owner: { name: "John Doe", phone: "1234567890", email: "john@example.com" },
    maxBookingHours: 2
  },
  {
    name: "MG Road Badminton Arena",
    sportType: "Badminton",
    location: "MG Road, Kochi",
    latitude: 9.9805,
    longitude: 76.2995,
    map: "https://www.google.com/maps?q=9.9805,76.2995&output=embed",
    size: "13.4x6.1 m",
    playerCount: 4,
    courtType: "Indoor, Synthetic",
    bookingCharge: 350,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/badminton2.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Shuttlecocks", "Rackets", "Scoreboard"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true }
    ],
    rating: 4.3,
    reviews: ["Good court", "Perfect for practice"],
    owner: { name: "Anjali Menon", phone: "9876543210", email: "anjali@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Badminton Hall",
    sportType: "Badminton",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "13.4x6.1 m",
    playerCount: 4,
    courtType: "Indoor, Wooden",
    bookingCharge: 250,
    lighting: "No",
    photos: ["https://example.com/photos/badminton3.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Shuttlecocks", "Rackets"],
    slots: [
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false }
    ],
    rating: 4.0,
    reviews: ["Nice court", "Good for doubles practice"],
    owner: { name: "Ravi Kumar", phone: "9012345678", email: "ravi@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Badminton Complex",
    sportType: "Badminton",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "13.4x6.1 m",
    playerCount: 4,
    courtType: "Indoor, Synthetic",
    bookingCharge: 320,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/badminton4.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Shuttlecocks", "Rackets", "Scoreboard"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true }
    ],
    rating: 4.6,
    reviews: ["Perfect indoor court", "Well-maintained floor"],
    owner: { name: "Sana Thomas", phone: "9988776655", email: "sana@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vytilla Badminton Arena",
    sportType: "Badminton",
    location: "Vytilla, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "13.4x6.1 m",
    playerCount: 4,
    courtType: "Indoor, Wooden",
    bookingCharge: 300,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/badminton5.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Shuttlecocks", "Rackets", "Scoreboard"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.4,
    reviews: ["Well-kept court", "Good for practice"],
    owner: { name: "Vijay Sharma", phone: "9123456789", email: "vijay@example.com" },
    maxBookingHours: 2
  },


// ------------------- Boxing -------------------

{
    name: "Kaloor Boxing Gym",
    sportType: "Boxing",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "20x15 m",
    playerCount: 2,
    courtType: "Indoor, Ring",
    bookingCharge: 400,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/boxing1.jpg"],
    amenities: ["Locker Rooms", "Showers", "Seating"],
    equipmentAvailable: ["Boxing Rings", "Punching Bags", "Gloves", "Pads"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Great training space!", "Friendly coaches"],
    owner: { name: "Ajay Kumar", phone: "9876543210", email: "ajay@example.com" },
    maxBookingHours: 2
  },
  {
    name: "MG Road Boxing Arena",
    sportType: "Boxing",
    location: "MG Road, Kochi",
    latitude: 9.9805,
    longitude: 76.2995,
    map: "https://www.google.com/maps?q=9.9805,76.2995&output=embed",
    size: "25x18 m",
    playerCount: 2,
    courtType: "Indoor, Ring",
    bookingCharge: 450,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/boxing2.jpg"],
    amenities: ["Locker Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Punching Bags", "Gloves", "Pads", "Speed Bags"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true }
    ],
    rating: 4.6,
    reviews: ["Well-equipped gym", "Good sparring rings"],
    owner: { name: "Rahul Menon", phone: "9123456789", email: "rahul@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Boxing Club",
    sportType: "Boxing",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "22x16 m",
    playerCount: 2,
    courtType: "Indoor, Ring",
    bookingCharge: 350,
    lighting: "No",
    photos: ["https://example.com/photos/boxing3.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Boxing Rings", "Punching Bags", "Gloves"],
    slots: [
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false }
    ],
    rating: 4.3,
    reviews: ["Good gym for beginners", "Friendly staff"],
    owner: { name: "Sana Thomas", phone: "9988776655", email: "sana@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Boxing Center",
    sportType: "Boxing",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "24x17 m",
    playerCount: 2,
    courtType: "Indoor, Ring",
    bookingCharge: 420,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/boxing4.jpg"],
    amenities: ["Locker Rooms", "Seating", "Parking"],
    equipmentAvailable: ["Punching Bags", "Gloves", "Pads"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true }
    ],
    rating: 4.5,
    reviews: ["Clean and spacious", "Good coaches"],
    owner: { name: "Vijay Sharma", phone: "9123456780", email: "vijay@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vytilla Boxing Gym",
    sportType: "Boxing",
    location: "Vytilla, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "20x15 m",
    playerCount: 2,
    courtType: "Indoor, Ring",
    bookingCharge: 400,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/boxing5.jpg"],
    amenities: ["Locker Rooms", "Seating", "Parking"],
    equipmentAvailable: ["Boxing Rings", "Punching Bags", "Gloves", "Pads"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.4,
    reviews: ["Well-equipped gym", "Great for sparring"],
    owner: { name: "Ajay Kumar", phone: "9876543211", email: "ajay2@example.com" },
    maxBookingHours: 2
  },
  

// ------------------- Swimming -------------------

{
    name: "Kaloor Aquatic Center",
    sportType: "Swimming",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "25x12 m, 6 lanes",
    playerCount: 20, // Max swimmers per session
    courtType: "Indoor, Heated Pool",
    bookingCharge: 300,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/swimming1.jpg"],
    amenities: ["Locker Rooms", "Showers", "Seating", "Lifeguard"],
    equipmentAvailable: ["Kickboards", "Lane Ropes", "Swim Caps"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Clean and well-maintained", "Great for training"],
    owner: { name: "Ajay Kumar", phone: "9876543210", email: "ajay@example.com" },
    maxBookingHours: 2
  },
  {
    name: "MG Road Swimming Pool",
    sportType: "Swimming",
    location: "MG Road, Kochi",
    latitude: 9.9805,
    longitude: 76.2995,
    map: "https://www.google.com/maps?q=9.9805,76.2995&output=embed",
    size: "25x10 m, 5 lanes",
    playerCount: 15,
    courtType: "Indoor, Heated Pool",
    bookingCharge: 250,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/swimming2.jpg"],
    amenities: ["Locker Rooms", "Showers", "Lifeguard"],
    equipmentAvailable: ["Kickboards", "Lane Ropes"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true }
    ],
    rating: 4.5,
    reviews: ["Nice pool, clean water", "Friendly staff"],
    owner: { name: "Rahul Menon", phone: "9123456789", email: "rahul@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Swim Club",
    sportType: "Swimming",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "20x8 m, 4 lanes",
    playerCount: 12,
    courtType: "Indoor Pool",
    bookingCharge: 200,
    lighting: "No",
    photos: ["https://example.com/photos/swimming3.jpg"],
    amenities: ["Showers", "Seating"],
    equipmentAvailable: ["Lane Ropes", "Kickboards"],
    slots: [
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false }
    ],
    rating: 4.3,
    reviews: ["Good for beginners", "Clean facilities"],
    owner: { name: "Sana Thomas", phone: "9988776655", email: "sana@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Aqua Center",
    sportType: "Swimming",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "25x12 m, 6 lanes",
    playerCount: 20,
    courtType: "Indoor, Heated Pool",
    bookingCharge: 300,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/swimming4.jpg"],
    amenities: ["Locker Rooms", "Showers", "Lifeguard"],
    equipmentAvailable: ["Kickboards", "Lane Ropes", "Swim Caps"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: true }
    ],
    rating: 4.6,
    reviews: ["Great for lap swimming", "Friendly lifeguards"],
    owner: { name: "Vijay Sharma", phone: "9123456780", email: "vijay@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vytilla Swimming Arena",
    sportType: "Swimming",
    location: "Vytilla, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "20x10 m, 4 lanes",
    playerCount: 15,
    courtType: "Indoor Pool",
    bookingCharge: 250,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/swimming5.jpg"],
    amenities: ["Locker Rooms", "Showers", "Seating", "Lifeguard"],
    equipmentAvailable: ["Lane Ropes", "Kickboards"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.4,
    reviews: ["Well-maintained pool", "Good for kids and adults"],
    owner: { name: "Ajay Kumar", phone: "9876543211", email: "ajay2@example.com" },
    maxBookingHours: 2
  },
 


// ------------------- Yoga -------------------

{
    name: "Kaloor Yoga Studio",
    sportType: "Yoga",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "50 m²",
    playerCount: 20, // Max participants per session
    courtType: "Indoor Studio, Wooden Floor",
    bookingCharge: 200,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/yoga1.jpg"],
    amenities: ["Yoga Mats", "Changing Rooms", "Water"],
    equipmentAvailable: ["Blocks", "Straps", "Mats"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:30-08:30", isBooked: true },
      { time: "17:00-18:00", isBooked: false }
    ],
    rating: 4.8,
    reviews: ["Excellent instructors!", "Peaceful environment"],
    owner: { name: "Anita Nair", phone: "9876543210", email: "anita@example.com" },
    maxBookingHours: 2
  },
  {
    name: "MG Road Yoga Center",
    sportType: "Yoga",
    location: "MG Road, Kochi",
    latitude: 9.9805,
    longitude: 76.2995,
    map: "https://www.google.com/maps?q=9.9805,76.2995&output=embed",
    size: "60 m²",
    playerCount: 25,
    courtType: "Indoor Studio, Wooden Floor",
    bookingCharge: 250,
    lighting: "Yes, Natural and LED",
    photos: ["https://example.com/photos/yoga2.jpg"],
    amenities: ["Mats", "Showers", "Water"],
    equipmentAvailable: ["Mats", "Blocks", "Straps"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "18:00-19:00", isBooked: true },
      { time: "19:30-20:30", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Calm and spacious studio", "Good class timings"],
    owner: { name: "Ramesh Kumar", phone: "9123456789", email: "ramesh@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Yoga Hall",
    sportType: "Yoga",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "40 m²",
    playerCount: 15,
    courtType: "Indoor Studio, Wooden Floor",
    bookingCharge: 150,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/yoga3.jpg"],
    amenities: ["Mats", "Changing Area", "Water"],
    equipmentAvailable: ["Mats", "Blocks"],
    slots: [
      { time: "07:00-08:00", isBooked: false },
      { time: "08:30-09:30", isBooked: true },
      { time: "17:30-18:30", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Good for beginners", "Friendly instructors"],
    owner: { name: "Sana Thomas", phone: "9988776655", email: "sana@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Yoga Studio",
    sportType: "Yoga",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "55 m²",
    playerCount: 20,
    courtType: "Indoor Studio, Wooden Floor",
    bookingCharge: 220,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/yoga4.jpg"],
    amenities: ["Mats", "Changing Rooms", "Water"],
    equipmentAvailable: ["Mats", "Straps", "Blocks"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:30-08:30", isBooked: false },
      { time: "18:00-19:00", isBooked: true }
    ],
    rating: 4.6,
    reviews: ["Great environment", "Professional instructors"],
    owner: { name: "Vijay Sharma", phone: "9123456780", email: "vijay@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vytilla Yoga Arena",
    sportType: "Yoga",
    location: "Vytilla, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "50 m²",
    playerCount: 18,
    courtType: "Indoor Studio, Wooden Floor",
    bookingCharge: 200,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/yoga5.jpg"],
    amenities: ["Mats", "Changing Rooms", "Water"],
    equipmentAvailable: ["Mats", "Blocks", "Straps"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "17:30-18:30", isBooked: true },
      { time: "19:00-20:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Peaceful place", "Good class sizes"],
    owner: { name: "Ajay Kumar", phone: "9876543211", email: "ajay2@example.com" },
    maxBookingHours: 2
  },
  

// ------------------- Gym -------------------

{
    name: "Kaloor Fitness Gym",
    sportType: "Gym",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "200 m²",
    playerCount: 30, // Max people at a time
    courtType: "Indoor, Fitness Equipment Area",
    bookingCharge: 300,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/gym1.jpg"],
    amenities: ["Dumbbells", "Treadmills", "Changing Rooms", "Water"],
    equipmentAvailable: ["Dumbbells", "Treadmills", "Bench Press", "Ellipticals"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "18:00-19:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Well-equipped", "Clean and spacious"],
    owner: { name: "Rohit Sharma", phone: "9876543212", email: "rohit@example.com" },
    maxBookingHours: 2
  },
  {
    name: "MG Road Gym",
    sportType: "Gym",
    location: "MG Road, Kochi",
    latitude: 9.9805,
    longitude: 76.2995,
    map: "https://www.google.com/maps?q=9.9805,76.2995&output=embed",
    size: "180 m²",
    playerCount: 25,
    courtType: "Indoor, Cardio & Weights Zone",
    bookingCharge: 250,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/gym2.jpg"],
    amenities: ["Treadmills", "Dumbbells", "Showers"],
    equipmentAvailable: ["Treadmills", "Dumbbells", "Stationary Bikes"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
      { time: "18:30-19:30", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Friendly trainers", "Good environment"],
    owner: { name: "Anil Kumar", phone: "9123456781", email: "anil@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Gym Arena",
    sportType: "Gym",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "150 m²",
    playerCount: 20,
    courtType: "Indoor, Weights Area",
    bookingCharge: 200,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/gym3.jpg"],
    amenities: ["Weights", "Mats", "Water"],
    equipmentAvailable: ["Weights", "Pull-up Bars", "Benches"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:30-08:30", isBooked: true },
      { time: "18:00-19:00", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Clean gym", "Good staff"],
    owner: { name: "Sana Thomas", phone: "9988776656", email: "sana2@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Fitness Center",
    sportType: "Gym",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "220 m²",
    playerCount: 35,
    courtType: "Indoor, Cardio & Weight Area",
    bookingCharge: 300,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/gym4.jpg"],
    amenities: ["Treadmills", "Dumbbells", "Showers"],
    equipmentAvailable: ["Treadmills", "Dumbbells", "Exercise Bikes"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:30-08:30", isBooked: false },
      { time: "18:00-19:00", isBooked: true }
    ],
    rating: 4.7,
    reviews: ["Professional trainers", "Spacious and clean"],
    owner: { name: "Vijay Sharma", phone: "9123456782", email: "vijay2@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vytilla Gym Arena",
    sportType: "Gym",
    location: "Vytilla, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "200 m²",
    playerCount: 30,
    courtType: "Indoor, Equipment Area",
    bookingCharge: 280,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/gym5.jpg"],
    amenities: ["Weights", "Mats", "Showers"],
    equipmentAvailable: ["Weights", "Treadmills", "Ellipticals"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "17:30-18:30", isBooked: true },
      { time: "19:00-20:00", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Good atmosphere", "Helpful trainers"],
    owner: { name: "Ajay Kumar", phone: "9876543213", email: "ajay3@example.com" },
    maxBookingHours: 2
  },
  

// ------------------- Table Tennis -------------------

{
    name: "Kaloor Table Tennis Arena",
    sportType: "Table Tennis",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "10x5 m",
    playerCount: 4,
    courtType: "Indoor, Professional Table Tennis Tables",
    bookingCharge: 150,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tt1.jpg"],
    amenities: ["Seating", "Water", "Changing Rooms"],
    equipmentAvailable: ["Table Tennis Balls", "Rackets", "Scoreboards"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Great tables", "Well-lit and spacious"],
    owner: { name: "Ramesh Kumar", phone: "9876543210", email: "ramesh@example.com" },
    maxBookingHours: 2
  },
  {
    name: "MG Road Table Tennis Club",
    sportType: "Table Tennis",
    location: "MG Road, Kochi",
    latitude: 9.9805,
    longitude: 76.2995,
    map: "https://www.google.com/maps?q=9.9805,76.2995&output=embed",
    size: "12x6 m",
    playerCount: 4,
    courtType: "Indoor, Recreational Tables",
    bookingCharge: 120,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tt2.jpg"],
    amenities: ["Seating", "Water"],
    equipmentAvailable: ["Rackets", "Balls"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "18:00-19:00", isBooked: false }
    ],
    rating: 4.3,
    reviews: ["Friendly environment", "Good lighting"],
    owner: { name: "Anil Thomas", phone: "9123456783", email: "aniltt@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam TT Center",
    sportType: "Table Tennis",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "10x5 m",
    playerCount: 4,
    courtType: "Indoor, Professional Tables",
    bookingCharge: 150,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tt3.jpg"],
    amenities: ["Seating", "Water", "Scoreboards"],
    equipmentAvailable: ["Balls", "Rackets"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "17:30-18:30", isBooked: true },
      { time: "19:00-20:00", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Good maintenance", "Spacious"],
    owner: { name: "Sana George", phone: "9988776655", email: "sana.tt@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Table Tennis Hall",
    sportType: "Table Tennis",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "12x6 m",
    playerCount: 4,
    courtType: "Indoor, Recreational",
    bookingCharge: 130,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tt4.jpg"],
    amenities: ["Seating", "Water", "Changing Rooms"],
    equipmentAvailable: ["Balls", "Rackets"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:30-08:30", isBooked: true },
      { time: "18:00-19:00", isBooked: false }
    ],
    rating: 4.4,
    reviews: ["Well-lit tables", "Nice staff"],
    owner: { name: "Vijay Kumar", phone: "9123456784", email: "vijay.tt@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vytilla TT Arena",
    sportType: "Table Tennis",
    location: "Vytilla, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "10x5 m",
    playerCount: 4,
    courtType: "Indoor, Professional",
    bookingCharge: 150,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tt5.jpg"],
    amenities: ["Seating", "Scoreboards", "Water"],
    equipmentAvailable: ["Rackets", "Balls"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "17:30-18:30", isBooked: true },
      { time: "19:00-20:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Professional setup", "Friendly staff"],
    owner: { name: "Ajay Kumar", phone: "9876543214", email: "ajay.tt@example.com" },
    maxBookingHours: 2
  },
  

// ------------------- Hockey -------------------
 {
    name: "Kaloor Hockey Field",
    sportType: "Hockey",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "91.4x55 m",
    playerCount: 22,
    courtType: "Outdoor, AstroTurf",
    bookingCharge: 600,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/hockey1.jpg"],
    amenities: ["Changing Rooms", "Seating", "Parking"],
    equipmentAvailable: ["Hockey Balls", "Sticks", "Goals"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "18:00-19:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Well-maintained field", "Good lighting"],
    owner: { name: "Rakesh Menon", phone: "9123456785", email: "rakesh.hockey@example.com" },
    maxBookingHours: 2
  },
  {
    name: "MG Road Hockey Ground",
    sportType: "Hockey",
    location: "MG Road, Kochi",
    latitude: 9.9805,
    longitude: 76.2995,
    map: "https://www.google.com/maps?q=9.9805,76.2995&output=embed",
    size: "91.4x55 m",
    playerCount: 22,
    courtType: "Outdoor, Grass",
    bookingCharge: 500,
    lighting: "No",
    photos: ["https://example.com/photos/hockey2.jpg"],
    amenities: ["Seating", "Water"],
    equipmentAvailable: ["Hockey Sticks", "Balls"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "17:30-18:30", isBooked: true },
      { time: "19:00-20:00", isBooked: false }
    ],
    rating: 4.3,
    reviews: ["Natural grass field", "Good location"],
    owner: { name: "Ajith Kumar", phone: "9876543215", email: "ajith.hockey@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Hockey Arena",
    sportType: "Hockey",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "91.4x55 m",
    playerCount: 22,
    courtType: "Outdoor, Synthetic Turf",
    bookingCharge: 650,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/hockey3.jpg"],
    amenities: ["Changing Rooms", "Water", "Seating"],
    equipmentAvailable: ["Balls", "Goals", "Sticks"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "18:00-19:00", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Professional field", "Well-maintained turf"],
    owner: { name: "Suresh Nair", phone: "9988776656", email: "suresh.hockey@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Hockey Ground",
    sportType: "Hockey",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "91.4x55 m",
    playerCount: 22,
    courtType: "Outdoor, AstroTurf",
    bookingCharge: 600,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/hockey4.jpg"],
    amenities: ["Changing Rooms", "Seating", "Parking"],
    equipmentAvailable: ["Balls", "Sticks", "Goals"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:30-08:30", isBooked: true },
      { time: "18:00-19:00", isBooked: false }
    ],
    rating: 4.4,
    reviews: ["Good turf", "Nice staff"],
    owner: { name: "Vijay Thomas", phone: "9123456786", email: "vijay.hockey@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vytilla Hockey Stadium",
    sportType: "Hockey",
    location: "Vytilla, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "91.4x55 m",
    playerCount: 22,
    courtType: "Outdoor, Synthetic Turf",
    bookingCharge: 650,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/hockey5.jpg"],
    amenities: ["Seating", "Changing Rooms", "Water"],
    equipmentAvailable: ["Sticks", "Balls", "Goals"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "17:30-18:30", isBooked: true },
      { time: "19:00-20:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Professional turf", "Well-managed"],
    owner: { name: "Ajay Kumar", phone: "9876543216", email: "ajay.hockey@example.com" },
    maxBookingHours: 2
  },
  

// ------------------- Cycling -------------------

{
    name: "Marine Drive Cycling Track",
    sportType: "Cycling",
    location: "Marine Drive, Kochi",
    latitude: 9.9660,
    longitude: 76.2910,
    map: "https://www.google.com/maps?q=9.9660,76.2910&output=embed",
    size: "5 km loop",
    playerCount: 1,
    courtType: "Outdoor, Asphalt",
    bookingCharge: 100,
    lighting: "Yes, Streetlights",
    photos: ["https://example.com/photos/cycling1.jpg"],
    amenities: ["Water Stations", "Seating", "Parking"],
    equipmentAvailable: ["Bikes", "Helmets"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "18:00-19:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Smooth track", "Beautiful route"],
    owner: { name: "Ravi Menon", phone: "9123456780", email: "ravi.cycling@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vyttila Cycling Loop",
    sportType: "Cycling",
    location: "Vyttila, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "3 km loop",
    playerCount: 1,
    courtType: "Outdoor, Asphalt",
    bookingCharge: 80,
    lighting: "No",
    photos: ["https://example.com/photos/cycling2.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Bikes"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "17:30-18:30", isBooked: true },
      { time: "19:00-20:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Safe track", "Good for training"],
    owner: { name: "Ajith Kumar", phone: "9876543210", email: "ajith.cycling@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Kaloor Cycling Track",
    sportType: "Cycling",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "4 km loop",
    playerCount: 1,
    courtType: "Outdoor, Concrete",
    bookingCharge: 90,
    lighting: "Yes, Streetlights",
    photos: ["https://example.com/photos/cycling3.jpg"],
    amenities: ["Seating", "Water"],
    equipmentAvailable: ["Bikes", "Helmets"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "18:00-19:00", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Well-marked track", "Good for beginners"],
    owner: { name: "Suresh Nair", phone: "9988776650", email: "suresh.cycling@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Riverside Cycling Path",
    sportType: "Cycling",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "6 km loop",
    playerCount: 1,
    courtType: "Outdoor, Asphalt",
    bookingCharge: 120,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/cycling4.jpg"],
    amenities: ["Parking", "Seating", "Water Stations"],
    equipmentAvailable: ["Bikes", "Helmets"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "18:00-19:00", isBooked: false }
    ],
    rating: 4.8,
    reviews: ["Scenic path", "Smooth surface"],
    owner: { name: "Vijay Thomas", phone: "9123456789", email: "vijay.cycling@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Cycling Route",
    sportType: "Cycling",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "5 km loop",
    playerCount: 1,
    courtType: "Outdoor, Asphalt",
    bookingCharge: 110,
    lighting: "No",
    photos: ["https://example.com/photos/cycling5.jpg"],
    amenities: ["Seating", "Water", "Parking"],
    equipmentAvailable: ["Bikes", "Helmets"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "17:30-18:30", isBooked: true },
      { time: "19:00-20:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Quiet and safe route", "Good for training"],
    owner: { name: "Ajay Kumar", phone: "9876543212", email: "ajay.cycling@example.com" },
    maxBookingHours: 2
  },
  


// ------------------- Skating -------------------
{
    name: "Ernakulam Ice Skating Rink",
    sportType: "Skating",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "50x25 m",
    playerCount: 20,
    courtType: "Indoor, Synthetic",
    bookingCharge: 200,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/skating1.jpg"],
    amenities: ["Seating", "Changing Rooms", "Parking"],
    equipmentAvailable: ["Skates", "Helmets", "Pads"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Great rink!", "Perfect for practice"],
    owner: { name: "Ramesh Kumar", phone: "9123456781", email: "ramesh.skating@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Kaloor Skating Arena",
    sportType: "Skating",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "60x30 m",
    playerCount: 25,
    courtType: "Indoor, Wooden",
    bookingCharge: 250,
    lighting: "Yes",
    photos: ["https://example.com/photos/skating2.jpg"],
    amenities: ["Seating", "Locker Room"],
    equipmentAvailable: ["Skates", "Helmets", "Pads"],
    slots: [
      { time: "10:30-11:30", isBooked: false },
      { time: "11:30-12:30", isBooked: true },
      { time: "12:30-13:30", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Clean and safe rink", "Good for beginners"],
    owner: { name: "Ajith Menon", phone: "9876543213", email: "ajith.skating@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Marine Drive Skating Zone",
    sportType: "Skating",
    location: "Marine Drive, Kochi",
    latitude: 9.9660,
    longitude: 76.2910,
    map: "https://www.google.com/maps?q=9.9660,76.2910&output=embed",
    size: "55x28 m",
    playerCount: 20,
    courtType: "Indoor, Synthetic",
    bookingCharge: 220,
    lighting: "Yes",
    photos: ["https://example.com/photos/skating3.jpg"],
    amenities: ["Parking", "Changing Rooms"],
    equipmentAvailable: ["Skates", "Helmets"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Excellent facility", "Friendly staff"],
    owner: { name: "Suresh Nair", phone: "9988776651", email: "suresh.skating@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vyttila Skating Hall",
    sportType: "Skating",
    location: "Vyttila, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "50x25 m",
    playerCount: 15,
    courtType: "Indoor, Wooden",
    bookingCharge: 180,
    lighting: "Yes",
    photos: ["https://example.com/photos/skating4.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Skates", "Pads"],
    slots: [
      { time: "11:00-12:00", isBooked: false },
      { time: "12:00-13:00", isBooked: true },
      { time: "13:00-14:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Safe and fun", "Good for practice"],
    owner: { name: "Vijay Thomas", phone: "9123456782", email: "vijay.skating@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Skating Park",
    sportType: "Skating",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "45x20 m",
    playerCount: 15,
    courtType: "Outdoor, Concrete",
    bookingCharge: 150,
    lighting: "No",
    photos: ["https://example.com/photos/skating5.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Skates", "Helmets"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false }
    ],
    rating: 4.4,
    reviews: ["Nice outdoor rink", "Good for practice"],
    owner: { name: "Ajay Kumar", phone: "9876543214", email: "ajay.skating@example.com" },
    maxBookingHours: 2
  },
  


// ------------------- Golf -------------------

{
    name: "Kochi Golf Club",
    sportType: "Golf",
    location: "Kochi",
    latitude: 9.9650,
    longitude: 76.2540,
    map: "https://www.google.com/maps?q=9.9650,76.2540&output=embed",
    size: "18 holes",
    playerCount: 4,
    courtType: "Outdoor, Grass",
    bookingCharge: 1000,
    lighting: "No",
    photos: ["https://example.com/photos/golf1.jpg"],
    amenities: ["Clubhouse", "Parking", "Cafeteria"],
    equipmentAvailable: ["Golf Clubs", "Balls", "Trolleys"],
    slots: [
      { time: "06:00-08:00", isBooked: false },
      { time: "08:00-10:00", isBooked: true },
      { time: "10:00-12:00", isBooked: false }
    ],
    rating: 4.8,
    reviews: ["Excellent course", "Well-maintained greens"],
    owner: { name: "Ravi Menon", phone: "9123456783", email: "ravi.golf@example.com" },
    maxBookingHours: 4
  },
  {
    name: "Marine Drive Golf Course",
    sportType: "Golf",
    location: "Marine Drive, Kochi",
    latitude: 9.9660,
    longitude: 76.2910,
    map: "https://www.google.com/maps?q=9.9660,76.2910&output=embed",
    size: "9 holes",
    playerCount: 4,
    courtType: "Outdoor, Grass",
    bookingCharge: 700,
    lighting: "No",
    photos: ["https://example.com/photos/golf2.jpg"],
    amenities: ["Parking", "Cafeteria"],
    equipmentAvailable: ["Golf Clubs", "Balls"],
    slots: [
      { time: "06:00-08:00", isBooked: false },
      { time: "08:00-10:00", isBooked: true },
      { time: "10:00-12:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Nice course", "Beautiful scenery"],
    owner: { name: "Ajith Kumar", phone: "9876543215", email: "ajith.golf@example.com" },
    maxBookingHours: 4
  },
  {
    name: "Kaloor Golf Arena",
    sportType: "Golf",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "9 holes",
    playerCount: 4,
    courtType: "Outdoor, Grass",
    bookingCharge: 800,
    lighting: "No",
    photos: ["https://example.com/photos/golf3.jpg"],
    amenities: ["Clubhouse", "Parking"],
    equipmentAvailable: ["Golf Clubs", "Balls", "Trolleys"],
    slots: [
      { time: "06:00-08:00", isBooked: false },
      { time: "08:00-10:00", isBooked: true },
      { time: "10:00-12:00", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Good layout", "Well-maintained"],
    owner: { name: "Suresh Nair", phone: "9988776652", email: "suresh.golf@example.com" },
    maxBookingHours: 4
  },
  {
    name: "Ernakulam Golf Club",
    sportType: "Golf",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "18 holes",
    playerCount: 4,
    courtType: "Outdoor, Grass",
    bookingCharge: 1200,
    lighting: "No",
    photos: ["https://example.com/photos/golf4.jpg"],
    amenities: ["Clubhouse", "Parking", "Cafeteria"],
    equipmentAvailable: ["Golf Clubs", "Balls", "Trolleys"],
    slots: [
      { time: "06:00-08:00", isBooked: false },
      { time: "08:00-10:00", isBooked: true },
      { time: "10:00-12:00", isBooked: false }
    ],
    rating: 4.9,
    reviews: ["Excellent greens", "Professional staff"],
    owner: { name: "Vijay Thomas", phone: "9123456784", email: "vijay.golf@example.com" },
    maxBookingHours: 4
  },
  {
    name: "Fort Kochi Golf Grounds",
    sportType: "Golf",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "9 holes",
    playerCount: 4,
    courtType: "Outdoor, Grass",
    bookingCharge: 750,
    lighting: "No",
    photos: ["https://example.com/photos/golf5.jpg"],
    amenities: ["Parking", "Clubhouse"],
    equipmentAvailable: ["Golf Clubs", "Balls"],
    slots: [
      { time: "06:00-08:00", isBooked: false },
      { time: "08:00-10:00", isBooked: true },
      { time: "10:00-12:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Nice small course", "Good for beginners"],
    owner: { name: "Ajay Kumar", phone: "9876543216", email: "ajay.golf@example.com" },
    maxBookingHours: 4
  },
  

// ------------------- Martial Arts -------------------
{
    name: "Kochi Martial Arts Academy",
    sportType: "Martial Arts",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "20x15 m",
    playerCount: 20,
    courtType: "Indoor, Wooden",
    bookingCharge: 300,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/ma1.jpg"],
    amenities: ["Changing Rooms", "Seating", "Parking"],
    equipmentAvailable: ["Punching Bags", "Mats", "Gloves"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Great trainers!", "Clean and safe"],
    owner: { name: "Ramesh Kumar", phone: "9123456787", email: "ramesh.ma@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Martial Arts Center",
    sportType: "Martial Arts",
    location: "Ernakulam, Kochi",
    latitude: 9.9820,
    longitude: 76.3050,
    map: "https://www.google.com/maps?q=9.9820,76.3050&output=embed",
    size: "25x20 m",
    playerCount: 25,
    courtType: "Indoor, Wooden",
    bookingCharge: 350,
    lighting: "Yes",
    photos: ["https://example.com/photos/ma2.jpg"],
    amenities: ["Changing Rooms", "Seating"],
    equipmentAvailable: ["Mats", "Gloves", "Pads"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: true },
      { time: "11:00-12:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Professional training", "Good atmosphere"],
    owner: { name: "Ajith Menon", phone: "9876543218", email: "ajith.ma@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Kaloor Martial Arts Arena",
    sportType: "Martial Arts",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "30x20 m",
    playerCount: 30,
    courtType: "Indoor, Wooden",
    bookingCharge: 400,
    lighting: "Yes",
    photos: ["https://example.com/photos/ma3.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Punching Bags", "Mats"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Excellent instructors", "Spacious hall"],
    owner: { name: "Suresh Nair", phone: "9988776653", email: "suresh.ma@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Martial Arts Hall",
    sportType: "Martial Arts",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "20x15 m",
    playerCount: 20,
    courtType: "Indoor, Wooden",
    bookingCharge: 250,
    lighting: "Yes",
    photos: ["https://example.com/photos/ma4.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Gloves", "Mats"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.4,
    reviews: ["Good for beginners", "Friendly trainers"],
    owner: { name: "Vijay Thomas", phone: "9123456785", email: "vijay.ma@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vyttila Martial Arts Center",
    sportType: "Martial Arts",
    location: "Vyttila, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "25x15 m",
    playerCount: 25,
    courtType: "Indoor, Wooden",
    bookingCharge: 300,
    lighting: "Yes",
    photos: ["https://example.com/photos/ma5.jpg"],
    amenities: ["Changing Rooms", "Parking"],
    equipmentAvailable: ["Mats", "Pads", "Gloves"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: true },
      { time: "11:00-12:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Safe and clean", "Good for sparring"],
    owner: { name: "Ajay Kumar", phone: "9876543217", email: "ajay.ma@example.com" },
    maxBookingHours: 2
  },
  


// ------------------- Archery -------------------

{
    name: "Kochi Archery Range",
    sportType: "Archery",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "50x10 m",
    playerCount: 10,
    courtType: "Outdoor, Grass",
    bookingCharge: 400,
    lighting: "No",
    photos: ["https://example.com/photos/archery1.jpg"],
    amenities: ["Seating", "Parking", "Changing Rooms"],
    equipmentAvailable: ["Bows", "Arrows", "Targets"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Safe and fun", "Professional guidance"],
    owner: { name: "Ravi Menon", phone: "9123456786", email: "ravi.archery@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Marine Drive Archery Range",
    sportType: "Archery",
    location: "Marine Drive, Kochi",
    latitude: 9.9660,
    longitude: 76.2910,
    map: "https://www.google.com/maps?q=9.9660,76.2910&output=embed",
    size: "60x15 m",
    playerCount: 12,
    courtType: "Outdoor, Grass",
    bookingCharge: 450,
    lighting: "No",
    photos: ["https://example.com/photos/archery2.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Bows", "Arrows", "Targets"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "07:30-08:30", isBooked: true },
      { time: "08:30-09:30", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Well-maintained", "Good for practice"],
    owner: { name: "Ajith Kumar", phone: "9876543219", email: "ajith.archery@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Kaloor Archery Club",
    sportType: "Archery",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "55x12 m",
    playerCount: 10,
    courtType: "Outdoor, Grass",
    bookingCharge: 420,
    lighting: "No",
    photos: ["https://example.com/photos/archery3.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Bows", "Arrows", "Targets"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Excellent for beginners", "Safe range"],
    owner: { name: "Suresh Nair", phone: "9988776654", email: "suresh.archery@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Archery Grounds",
    sportType: "Archery",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "50x10 m",
    playerCount: 8,
    courtType: "Outdoor, Grass",
    bookingCharge: 400,
    lighting: "No",
    photos: ["https://example.com/photos/archery4.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Bows", "Arrows"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Great place to practice", "Friendly staff"],
    owner: { name: "Vijay Thomas", phone: "9123456788", email: "vijay.archery@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vyttila Archery Range",
    sportType: "Archery",
    location: "Vyttila, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "55x12 m",
    playerCount: 10,
    courtType: "Outdoor, Grass",
    bookingCharge: 430,
    lighting: "No",
    photos: ["https://example.com/photos/archery5.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Bows", "Arrows", "Targets"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Safe and organized", "Good for training"],
    owner: { name: "Ajay Kumar", phone: "9876543210", email: "ajay.archery@example.com" },
    maxBookingHours: 2
  },
  

// ------------------- Rock Climbing -------------------

{
    name: "Kochi Rock Climbing Arena",
    sportType: "Rock Climbing",
    location: "Ernakulam, Kochi",
    latitude: 9.9815,
    longitude: 76.3000,
    map: "https://www.google.com/maps?q=9.9815,76.3000&output=embed",
    size: "15x20 m",
    playerCount: 10,
    courtType: "Indoor, Artificial Wall",
    bookingCharge: 500,
    lighting: "Yes",
    photos: ["https://example.com/photos/rc1.jpg"],
    amenities: ["Changing Rooms", "Seating", "Parking"],
    equipmentAvailable: ["Harnesses", "Ropes", "Helmets"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Safe and fun", "Good trainers"],
    owner: { name: "Ravi Menon", phone: "9123456790", email: "ravi.rc@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Climbing Club",
    sportType: "Rock Climbing",
    location: "Fort Kochi, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "20x25 m",
    playerCount: 15,
    courtType: "Indoor, Artificial Wall",
    bookingCharge: 550,
    lighting: "Yes",
    photos: ["https://example.com/photos/rc2.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Ropes", "Mats", "Harnesses"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: true },
      { time: "11:00-12:00", isBooked: false }
    ],
    rating: 4.5,
    reviews: ["Great for beginners", "Well-maintained"],
    owner: { name: "Ajith Kumar", phone: "9876543220", email: "ajith.rc@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Kaloor Climbing Wall",
    sportType: "Rock Climbing",
    location: "Kaloor, Kochi",
    latitude: 9.9980,
    longitude: 76.3070,
    map: "https://www.google.com/maps?q=9.9980,76.3070&output=embed",
    size: "25x20 m",
    playerCount: 20,
    courtType: "Indoor, Artificial Wall",
    bookingCharge: 600,
    lighting: "Yes",
    photos: ["https://example.com/photos/rc3.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Helmets", "Harnesses", "Ropes"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.8,
    reviews: ["Excellent instructors", "Safe setup"],
    owner: { name: "Suresh Nair", phone: "9988776655", email: "suresh.rc@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vyttila Rock Climbing Hub",
    sportType: "Rock Climbing",
    location: "Vyttila, Kochi",
    latitude: 9.9755,
    longitude: 76.3005,
    map: "https://www.google.com/maps?q=9.9755,76.3005&output=embed",
    size: "20x20 m",
    playerCount: 15,
    courtType: "Indoor, Artificial Wall",
    bookingCharge: 500,
    lighting: "Yes",
    photos: ["https://example.com/photos/rc4.jpg"],
    amenities: ["Changing Rooms", "Parking"],
    equipmentAvailable: ["Ropes", "Helmets", "Mats"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: true },
      { time: "11:00-12:00", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Spacious hall", "Friendly staff"],
    owner: { name: "Vijay Thomas", phone: "9123456791", email: "vijay.rc@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Ernakulam Climbing Arena",
    sportType: "Rock Climbing",
    location: "Ernakulam, Kochi",
    latitude: 9.9820,
    longitude: 76.3050,
    map: "https://www.google.com/maps?q=9.9820,76.3050&output=embed",
    size: "25x25 m",
    playerCount: 20,
    courtType: "Indoor, Artificial Wall",
    bookingCharge: 550,
    lighting: "Yes",
    photos: ["https://example.com/photos/rc5.jpg"],
    amenities: ["Seating", "Changing Rooms"],
    equipmentAvailable: ["Harnesses", "Ropes", "Gloves"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Safe and fun", "Professional training"],
    owner: { name: "Ajay Kumar", phone: "9876543221", email: "ajay.rc@example.com" },
    maxBookingHours: 2
  },
  

// ------------------- Surfing -------------------

{
    name: "Cherai Surfing School",
    sportType: "Surfing",
    location: "Cherai Beach, Kochi",
    latitude: 10.0650,
    longitude: 76.1680,
    map: "https://www.google.com/maps?q=10.0650,76.1680&output=embed",
    size: "Beach Area",
    playerCount: 10,
    courtType: "Outdoor, Beach",
    bookingCharge: 600,
    lighting: "No",
    photos: ["https://example.com/photos/surf1.jpg"],
    amenities: ["Parking", "Changing Rooms"],
    equipmentAvailable: ["Surfboards", "Wetsuits", "Life Jackets"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Great waves!", "Friendly instructors"],
    owner: { name: "Ramesh Kumar", phone: "9123456792", email: "ramesh.surf@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Fort Kochi Surf Club",
    sportType: "Surfing",
    location: "Fort Kochi Beach, Kochi",
    latitude: 9.9655,
    longitude: 76.2425,
    map: "https://www.google.com/maps?q=9.9655,76.2425&output=embed",
    size: "Beach Area",
    playerCount: 12,
    courtType: "Outdoor, Beach",
    bookingCharge: 650,
    lighting: "No",
    photos: ["https://example.com/photos/surf2.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Surfboards", "Life Jackets"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "07:30-08:30", isBooked: true },
      { time: "08:30-09:30", isBooked: false }
    ],
    rating: 4.6,
    reviews: ["Safe for beginners", "Good trainers"],
    owner: { name: "Ajith Kumar", phone: "9876543222", email: "ajith.surf@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Vypeen Surfing Hub",
    sportType: "Surfing",
    location: "Vypeen Island, Kochi",
    latitude: 10.0150,
    longitude: 76.2100,
    map: "https://www.google.com/maps?q=10.0150,76.2100&output=embed",
    size: "Beach Area",
    playerCount: 15,
    courtType: "Outdoor, Beach",
    bookingCharge: 700,
    lighting: "No",
    photos: ["https://example.com/photos/surf3.jpg"],
    amenities: ["Changing Rooms", "Parking"],
    equipmentAvailable: ["Surfboards", "Wetsuits"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.8,
    reviews: ["Amazing experience", "Beautiful location"],
    owner: { name: "Suresh Nair", phone: "9988776656", email: "suresh.surf@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Cherai Waves Surfing",
    sportType: "Surfing",
    location: "Cherai Beach, Kochi",
    latitude: 10.0655,
    longitude: 76.1690,
    map: "https://www.google.com/maps?q=10.0655,76.1690&output=embed",
    size: "Beach Area",
    playerCount: 12,
    courtType: "Outdoor, Beach",
    bookingCharge: 650,
    lighting: "No",
    photos: ["https://example.com/photos/surf4.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Surfboards", "Life Jackets", "Wetsuits"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false }
    ],
    rating: 4.7,
    reviews: ["Professional instructors", "Safe for beginners"],
    owner: { name: "Vijay Thomas", phone: "9123456793", email: "vijay.surf@example.com" },
    maxBookingHours: 2
  },
  {
    name: "Marine Drive Surf School",
    sportType: "Surfing",
    location: "Marine Drive, Kochi",
    latitude: 9.9660,
    longitude: 76.2910,
    map: "https://www.google.com/maps?q=9.9660,76.2910&output=embed",
    size: "Beach Area",
    playerCount: 15,
    courtType: "Outdoor, Beach",
    bookingCharge: 700,
    lighting: "No",
    photos: ["https://example.com/photos/surf5.jpg"],
    amenities: ["Parking", "Changing Rooms"],
    equipmentAvailable: ["Surfboards", "Wetsuits", "Life Jackets"],
    slots: [
      { time: "06:30-07:30", isBooked: false },
      { time: "07:30-08:30", isBooked: true },
      { time: "08:30-09:30", isBooked: false }
    ],
    rating: 4.8,
    reviews: ["Best surfing spot", "Amazing instructors"],
    owner: { name: "Ajay Kumar", phone: "9876543223", email: "ajay.surf@example.com" },
    maxBookingHours: 2
  },
  
];








