const courts = [
  // ------------------- Basketball -------------------
  {
    name: "Downtown Basketball Court",
    sportType: "Basketball",
    location: "Downtown, City Center",
    latitude: 12.9716,
    longitude: 77.5946,
    size: "28x15 m",
    playerCount: 10,
    courtType: "Indoor, Hardwood",
    bookingCharge: 500,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/basketball1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Basketballs", "Scoreboard"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false },
    ],
    rating: 4.5,
    reviews: ["Great court!", "Well-maintained!"],
    owner: { name: "John Doe", phone: "1234567890", email: "john@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Basketball Court",
    sportType: "Basketball",
    location: "Central Park",
    latitude: 12.9780,
    longitude: 77.5970,
    size: "28x15 m",
    playerCount: 10,
    courtType: "Outdoor, Concrete",
    bookingCharge: 450,
    lighting: "No",
    photos: ["https://example.com/photos/basketball2.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Basketballs"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
    ],
    rating: 4.2,
    reviews: ["Good for casual games.", "Nice open space."],
    owner: { name: "Alice Smith", phone: "9876543210", email: "alice@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Basketball Arena",
    sportType: "Basketball",
    location: "Eastside District",
    latitude: 12.9805,
    longitude: 77.6010,
    size: "28x15 m",
    playerCount: 10,
    courtType: "Indoor, Hardwood",
    bookingCharge: 520,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/basketball3.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Basketballs", "Scoreboard", "Hoops"],
    slots: [
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Excellent facility!", "Perfect lighting."],
    owner: { name: "Mark Taylor", phone: "9988776655", email: "mark@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Westside Sports Court",
    sportType: "Basketball",
    location: "Westside",
    latitude: 12.9650,
    longitude: 77.5900,
    size: "28x15 m",
    playerCount: 10,
    courtType: "Outdoor, Concrete",
    bookingCharge: 400,
    lighting: "No",
    photos: ["https://example.com/photos/basketball4.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Basketballs"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: true },
      { time: "14:00-15:00", isBooked: false },
    ],
    rating: 4.0,
    reviews: ["Decent court.", "Good location."],
    owner: { name: "Sophie Lee", phone: "1122445566", email: "sophie@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Basketball Court",
    sportType: "Basketball",
    location: "Uptown",
    latitude: 12.9900,
    longitude: 77.6050,
    size: "28x15 m",
    playerCount: 10,
    courtType: "Indoor, Hardwood",
    bookingCharge: 550,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/basketball5.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Basketballs", "Scoreboard", "Hoops"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Professional court!", "Loved the experience."],
    owner: { name: "Emma Brown", phone: "5566778899", email: "emma@example.com" },
    maxBookingHours: 3,
  },

  // ------------------- Tennis -------------------
  {
    name: "Riverside Tennis Court",
    sportType: "Tennis",
    location: "Riverside Park",
    latitude: 12.9721,
    longitude: 77.5935,
    size: "23.77x10.97 m",
    playerCount: 2,
    courtType: "Outdoor, Hardcourt",
    bookingCharge: 300,
    lighting: "No",
    photos: ["https://example.com/photos/tennis1.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Rackets", "Balls"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: false },
      { time: "12:00-13:00", isBooked: true },
    ],
    rating: 4.2,
    reviews: ["Perfect for doubles!", "Good sunlight"],
    owner: { name: "Bob Johnson", phone: "1122334455", email: "bob@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Tennis Court",
    sportType: "Tennis",
    location: "Central Park",
    latitude: 12.9780,
    longitude: 77.5970,
    size: "23.77x10.97 m",
    playerCount: 2,
    courtType: "Indoor, Synthetic",
    bookingCharge: 350,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tennis2.jpg"],
    amenities: ["Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Rackets", "Balls", "Net"],
    slots: [
      { time: "09:00-10:00", isBooked: true },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Great indoor court!", "Perfect for practice"],
    owner: { name: "Alice White", phone: "9988776655", email: "alice@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Lakeside Tennis Court",
    sportType: "Tennis",
    location: "Lakeside",
    latitude: 12.9815,
    longitude: 77.5985,
    size: "23.77x10.97 m",
    playerCount: 2,
    courtType: "Outdoor, Clay",
    bookingCharge: 320,
    lighting: "No",
    photos: ["https://example.com/photos/tennis3.jpg"],
    amenities: ["Parking", "Seating", "Changing Rooms"],
    equipmentAvailable: ["Rackets", "Balls"],
    slots: [
      { time: "08:00-09:00", isBooked: false },
      { time: "09:00-10:00", isBooked: true },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.3,
    reviews: ["Nice clay court.", "Good for practice."],
    owner: { name: "David Green", phone: "6677889900", email: "david@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Hilltop Tennis Arena",
    sportType: "Tennis",
    location: "Hilltop District",
    latitude: 12.9850,
    longitude: 77.6000,
    size: "23.77x10.97 m",
    playerCount: 2,
    courtType: "Indoor, Hardcourt",
    bookingCharge: 400,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tennis4.jpg"],
    amenities: ["Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Rackets", "Balls", "Net"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: false },
      { time: "14:00-15:00", isBooked: true },
    ],
    rating: 4.7,
    reviews: ["Excellent indoor facility.", "Perfect lighting."],
    owner: { name: "Linda Brown", phone: "2233445566", email: "linda@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Uptown Tennis Club",
    sportType: "Tennis",
    location: "Uptown",
    latitude: 12.9905,
    longitude: 77.6055,
    size: "23.77x10.97 m",
    playerCount: 2,
    courtType: "Outdoor, Grass",
    bookingCharge: 370,
    lighting: "No",
    photos: ["https://example.com/photos/tennis5.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Rackets", "Balls"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
    ],
    rating: 4.5,
    reviews: ["Perfect for casual matches.", "Friendly staff."],
    owner: { name: "Karen Smith", phone: "3344556677", email: "karen@example.com" },
    maxBookingHours: 2,
  },
  
];

// ------------------- Football -------------------
const footballCourts = [
  {
    name: "Greenfield Football Stadium",
    sportType: "Football",
    location: "Greenfield, City Center",
    latitude: 12.9710,
    longitude: 77.5940,
    size: "105x68 m",
    playerCount: 22,
    courtType: "Outdoor, Grass",
    bookingCharge: 1000,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/football1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating", "Restrooms"],
    equipmentAvailable: ["Goals", "Balls", "Corner Flags"],
    slots: [
      { time: "09:00-11:00", isBooked: false },
      { time: "11:00-13:00", isBooked: true },
      { time: "14:00-16:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Great field!", "Well-maintained grass."],
    owner: { name: "Michael Scott", phone: "1234567891", email: "michael@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Football Arena",
    sportType: "Football",
    location: "Central Park",
    latitude: 12.9785,
    longitude: 77.5975,
    size: "100x64 m",
    playerCount: 22,
    courtType: "Outdoor, Artificial Turf",
    bookingCharge: 950,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/football2.jpg"],
    amenities: ["Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Goals", "Balls"],
    slots: [
      { time: "08:00-10:00", isBooked: false },
      { time: "10:00-12:00", isBooked: true },
      { time: "12:00-14:00", isBooked: false },
    ],
    rating: 4.5,
    reviews: ["Perfect turf!", "Good for practice matches."],
    owner: { name: "Sarah Johnson", phone: "9876543211", email: "sarah@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Football Field",
    sportType: "Football",
    location: "Eastside District",
    latitude: 12.9800,
    longitude: 77.6005,
    size: "105x68 m",
    playerCount: 22,
    courtType: "Outdoor, Grass",
    bookingCharge: 1100,
    lighting: "No",
    photos: ["https://example.com/photos/football3.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Goals", "Balls", "Corner Flags"],
    slots: [
      { time: "09:00-11:00", isBooked: true },
      { time: "11:00-13:00", isBooked: false },
      { time: "13:00-15:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Spacious field.", "Good maintenance."],
    owner: { name: "Robert Green", phone: "1122334456", email: "robert@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Westside Football Arena",
    sportType: "Football",
    location: "Westside",
    latitude: 12.9655,
    longitude: 77.5910,
    size: "100x65 m",
    playerCount: 22,
    courtType: "Indoor, Synthetic Turf",
    bookingCharge: 1200,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/football4.jpg"],
    amenities: ["Locker Rooms", "Seating", "Parking"],
    equipmentAvailable: ["Goals", "Balls", "Cones"],
    slots: [
      { time: "10:00-12:00", isBooked: false },
      { time: "12:00-14:00", isBooked: false },
      { time: "14:00-16:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Indoor facility is excellent!", "Great synthetic turf."],
    owner: { name: "Emma Watson", phone: "5566778890", email: "emma@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Football Stadium",
    sportType: "Football",
    location: "Uptown",
    latitude: 12.9910,
    longitude: 77.6060,
    size: "105x68 m",
    playerCount: 22,
    courtType: "Outdoor, Grass",
    bookingCharge: 1150,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/football5.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating", "Restrooms", "Cafeteria"],
    equipmentAvailable: ["Goals", "Balls", "Scoreboard"],
    slots: [
      { time: "15:00-17:00", isBooked: false },
      { time: "17:00-19:00", isBooked: true },
      { time: "19:00-21:00", isBooked: false },
    ],
    rating: 4.9,
    reviews: ["Perfect stadium for league matches.", "Very clean and professional."],
    owner: { name: "James Miller", phone: "6677889901", email: "james@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Volleyball -------------------
const volleyballCourts = [
  {
    name: "Downtown Volleyball Arena",
    sportType: "Volleyball",
    location: "Downtown, City Center",
    latitude: 12.9705,
    longitude: 77.5935,
    size: "18x9 m",
    playerCount: 12,
    courtType: "Indoor, Hardwood",
    bookingCharge: 400,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/volleyball1.jpg"],
    amenities: ["Changing Rooms", "Seating", "Parking", "Locker Rooms"],
    equipmentAvailable: ["Volleyballs", "Net", "Scoreboard"],
    slots: [
      { time: "09:00-10:30", isBooked: false },
      { time: "10:30-12:00", isBooked: true },
      { time: "12:00-13:30", isBooked: false },
    ],
    rating: 4.5,
    reviews: ["Excellent indoor court!", "Perfect for tournaments."],
    owner: { name: "Laura Brown", phone: "1234567892", email: "laura@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Volleyball Court",
    sportType: "Volleyball",
    location: "Central Park",
    latitude: 12.9770,
    longitude: 77.5965,
    size: "18x9 m",
    playerCount: 12,
    courtType: "Outdoor, Sand",
    bookingCharge: 350,
    lighting: "No",
    photos: ["https://example.com/photos/volleyball2.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Volleyballs", "Net"],
    slots: [
      { time: "08:00-09:30", isBooked: false },
      { time: "09:30-11:00", isBooked: true },
      { time: "11:00-12:30", isBooked: false },
    ],
    rating: 4.2,
    reviews: ["Great outdoor sand court.", "Perfect for practice."],
    owner: { name: "David Smith", phone: "9876543212", email: "david@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Volleyball Arena",
    sportType: "Volleyball",
    location: "Eastside District",
    latitude: 12.9805,
    longitude: 77.6000,
    size: "18x9 m",
    playerCount: 12,
    courtType: "Indoor, Synthetic",
    bookingCharge: 450,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/volleyball3.jpg"],
    amenities: ["Changing Rooms", "Seating", "Parking"],
    equipmentAvailable: ["Volleyballs", "Net", "Scoreboard"],
    slots: [
      { time: "09:00-10:30", isBooked: true },
      { time: "10:30-12:00", isBooked: false },
      { time: "12:00-13:30", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Excellent synthetic court!", "Great for matches."],
    owner: { name: "Sophie Lee", phone: "1122445567", email: "sophie@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Westside Volleyball Court",
    sportType: "Volleyball",
    location: "Westside",
    latitude: 12.9650,
    longitude: 77.5905,
    size: "18x9 m",
    playerCount: 12,
    courtType: "Outdoor, Sand",
    bookingCharge: 300,
    lighting: "No",
    photos: ["https://example.com/photos/volleyball4.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Volleyballs", "Net"],
    slots: [
      { time: "12:00-13:30", isBooked: false },
      { time: "13:30-15:00", isBooked: true },
      { time: "15:00-16:30", isBooked: false },
    ],
    rating: 4.0,
    reviews: ["Nice outdoor court.", "Good location."],
    owner: { name: "Emma Watson", phone: "5566778891", email: "emma@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Volleyball Arena",
    sportType: "Volleyball",
    location: "Uptown",
    latitude: 12.9905,
    longitude: 77.6055,
    size: "18x9 m",
    playerCount: 12,
    courtType: "Indoor, Hardwood",
    bookingCharge: 500,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/volleyball5.jpg"],
    amenities: ["Changing Rooms", "Seating", "Parking", "Locker Rooms"],
    equipmentAvailable: ["Volleyballs", "Net", "Scoreboard", "Cones"],
    slots: [
      { time: "15:00-16:30", isBooked: false },
      { time: "16:30-18:00", isBooked: false },
      { time: "18:00-19:30", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Professional indoor court!", "Great for tournaments."],
    owner: { name: "James Miller", phone: "6677889902", email: "james@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Badminton -------------------
const badmintonCourts = [
  {
    name: "Downtown Badminton Hall",
    sportType: "Badminton",
    location: "Downtown, City Center",
    latitude: 12.9718,
    longitude: 77.5948,
    size: "13.4x6.1 m",
    playerCount: 2,
    courtType: "Indoor, Wooden",
    bookingCharge: 250,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/badminton1.jpg"],
    amenities: ["Changing Rooms", "Seating", "Parking", "Locker Rooms"],
    equipmentAvailable: ["Rackets", "Shuttlecocks", "Net"],
    slots: [
      { time: "08:00-09:00", isBooked: false },
      { time: "09:00-10:00", isBooked: true },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Perfect indoor hall!", "Great for practice sessions."],
    owner: { name: "John Carter", phone: "1234567893", email: "john@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Badminton Court",
    sportType: "Badminton",
    location: "Central Park",
    latitude: 12.9785,
    longitude: 77.5975,
    size: "13.4x6.1 m",
    playerCount: 2,
    courtType: "Indoor, Synthetic",
    bookingCharge: 300,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/badminton2.jpg"],
    amenities: ["Seating", "Parking", "Locker Rooms"],
    equipmentAvailable: ["Rackets", "Shuttlecocks", "Net", "Scoreboard"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
    ],
    rating: 4.7,
    reviews: ["Excellent court for doubles!", "Indoor lighting is perfect."],
    owner: { name: "Alice Green", phone: "9876543213", email: "alice@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Badminton Arena",
    sportType: "Badminton",
    location: "Eastside District",
    latitude: 12.9810,
    longitude: 77.6015,
    size: "13.4x6.1 m",
    playerCount: 2,
    courtType: "Indoor, Wooden",
    bookingCharge: 280,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/badminton3.jpg"],
    amenities: ["Changing Rooms", "Seating", "Parking"],
    equipmentAvailable: ["Rackets", "Shuttlecocks", "Net"],
    slots: [
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.5,
    reviews: ["Great wooden flooring!", "Well-maintained."],
    owner: { name: "Mark Taylor", phone: "9988776656", email: "mark@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Westside Badminton Court",
    sportType: "Badminton",
    location: "Westside",
    latitude: 12.9655,
    longitude: 77.5910,
    size: "13.4x6.1 m",
    playerCount: 2,
    courtType: "Indoor, Synthetic",
    bookingCharge: 270,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/badminton4.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Rackets", "Shuttlecocks", "Net"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: true },
      { time: "14:00-15:00", isBooked: false },
    ],
    rating: 4.3,
    reviews: ["Good court for singles.", "Friendly staff."],
    owner: { name: "Sophie Lee", phone: "1122445568", email: "sophie@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Badminton Hall",
    sportType: "Badminton",
    location: "Uptown",
    latitude: 12.9910,
    longitude: 77.6060,
    size: "13.4x6.1 m",
    playerCount: 2,
    courtType: "Indoor, Wooden",
    bookingCharge: 320,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/badminton5.jpg"],
    amenities: ["Changing Rooms", "Seating", "Parking", "Locker Rooms"],
    equipmentAvailable: ["Rackets", "Shuttlecocks", "Net", "Scoreboard"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Professional indoor hall!", "Perfect for tournaments."],
    owner: { name: "Emma Brown", phone: "5566778892", email: "emma@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Boxing -------------------
const boxingGyms = [
  {
    name: "Downtown Boxing Club",
    sportType: "Boxing",
    location: "Downtown, City Center",
    latitude: 12.9720,
    longitude: 77.5950,
    size: "10x10 m",
    playerCount: 2,
    courtType: "Indoor, Ring",
    bookingCharge: 500,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/boxing1.jpg"],
    amenities: ["Locker Rooms", "Shower", "Parking", "Seating"],
    equipmentAvailable: ["Boxing Gloves", "Punching Bags", "Ring"],
    slots: [
      { time: "08:00-09:00", isBooked: false },
      { time: "09:00-10:00", isBooked: true },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Excellent training environment!", "Clean and spacious ring."],
    owner: { name: "John Carter", phone: "1234567800", email: "john@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Boxing Arena",
    sportType: "Boxing",
    location: "Central Park",
    latitude: 12.9782,
    longitude: 77.5972,
    size: "12x12 m",
    playerCount: 2,
    courtType: "Indoor, Ring",
    bookingCharge: 550,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/boxing2.jpg"],
    amenities: ["Locker Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Boxing Gloves", "Punching Bags", "Ring", "Speed Bag"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
    ],
    rating: 4.7,
    reviews: ["Great coaching available.", "Perfect for beginners."],
    owner: { name: "Alice Green", phone: "9876543210", email: "alice@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Boxing Club",
    sportType: "Boxing",
    location: "Eastside District",
    latitude: 12.9808,
    longitude: 77.6018,
    size: "10x10 m",
    playerCount: 2,
    courtType: "Indoor, Ring",
    bookingCharge: 500,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/boxing3.jpg"],
    amenities: ["Locker Rooms", "Shower", "Parking"],
    equipmentAvailable: ["Boxing Gloves", "Punching Bags"],
    slots: [
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.5,
    reviews: ["Good training environment.", "Friendly staff."],
    owner: { name: "Mark Taylor", phone: "9988776650", email: "mark@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Westside Boxing Gym",
    sportType: "Boxing",
    location: "Westside",
    latitude: 12.9652,
    longitude: 77.5912,
    size: "12x12 m",
    playerCount: 2,
    courtType: "Indoor, Ring",
    bookingCharge: 480,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/boxing4.jpg"],
    amenities: ["Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Boxing Gloves", "Punching Bags", "Ring"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: true },
      { time: "14:00-15:00", isBooked: false },
    ],
    rating: 4.3,
    reviews: ["Good indoor space for training.", "Equipment is well-maintained."],
    owner: { name: "Sophie Lee", phone: "1122445560", email: "sophie@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Boxing Academy",
    sportType: "Boxing",
    location: "Uptown",
    latitude: 12.9912,
    longitude: 77.6062,
    size: "10x10 m",
    playerCount: 2,
    courtType: "Indoor, Ring",
    bookingCharge: 600,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/boxing5.jpg"],
    amenities: ["Locker Rooms", "Shower", "Parking", "Seating"],
    equipmentAvailable: ["Boxing Gloves", "Punching Bags", "Ring", "Speed Bag"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Professional facility!", "Great trainers available."],
    owner: { name: "Emma Brown", phone: "5566778890", email: "emma@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Swimming -------------------
const swimmingPools = [
  {
    name: "Downtown Aquatic Center",
    sportType: "Swimming",
    location: "Downtown, City Center",
    latitude: 12.9715,
    longitude: 77.5945,
    size: "25x10 m",
    playerCount: 10,
    courtType: "Indoor, Heated",
    bookingCharge: 400,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/swimming1.jpg"],
    amenities: ["Locker Rooms", "Showers", "Parking", "Seating"],
    equipmentAvailable: ["Lanes", "Kickboards", "Floats"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Excellent pool!", "Clean and well-maintained."],
    owner: { name: "John Carter", phone: "1234567891", email: "johnc@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Swimming Club",
    sportType: "Swimming",
    location: "Central Park",
    latitude: 12.9781,
    longitude: 77.5971,
    size: "25x10 m",
    playerCount: 10,
    courtType: "Outdoor, Heated",
    bookingCharge: 350,
    lighting: "No",
    photos: ["https://example.com/photos/swimming2.jpg"],
    amenities: ["Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Lanes", "Kickboards", "Floats"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
    ],
    rating: 4.5,
    reviews: ["Good outdoor pool.", "Great for practice."],
    owner: { name: "Alice Green", phone: "9876543211", email: "aliceg@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Swimming Arena",
    sportType: "Swimming",
    location: "Eastside District",
    latitude: 12.9806,
    longitude: 77.6011,
    size: "25x12 m",
    playerCount: 10,
    courtType: "Indoor, Heated",
    bookingCharge: 420,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/swimming3.jpg"],
    amenities: ["Locker Rooms", "Showers", "Parking", "Seating"],
    equipmentAvailable: ["Lanes", "Kickboards", "Floats", "Lane Markers"],
    slots: [
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Perfect for swim training.", "Friendly staff."],
    owner: { name: "Mark Taylor", phone: "9988776651", email: "markt@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Westside Pool Complex",
    sportType: "Swimming",
    location: "Westside",
    latitude: 12.9651,
    longitude: 77.5901,
    size: "25x12 m",
    playerCount: 10,
    courtType: "Outdoor, Heated",
    bookingCharge: 380,
    lighting: "No",
    photos: ["https://example.com/photos/swimming4.jpg"],
    amenities: ["Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Lanes", "Kickboards"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: true },
      { time: "14:00-15:00", isBooked: false },
    ],
    rating: 4.4,
    reviews: ["Good for casual swimming.", "Nice outdoor setup."],
    owner: { name: "Sophie Lee", phone: "1122445561", email: "sophiel@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Swimming Academy",
    sportType: "Swimming",
    location: "Uptown",
    latitude: 12.9901,
    longitude: 77.6051,
    size: "25x10 m",
    playerCount: 10,
    courtType: "Indoor, Heated",
    bookingCharge: 450,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/swimming5.jpg"],
    amenities: ["Locker Rooms", "Showers", "Parking", "Seating", "Cafe"],
    equipmentAvailable: ["Lanes", "Kickboards", "Floats", "Lane Markers"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Professional coaching available!", "Loved the pool design."],
    owner: { name: "Emma Brown", phone: "5566778891", email: "emmab@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Yoga -------------------
const yogaStudios = [
  {
    name: "Downtown Yoga Center",
    sportType: "Yoga",
    location: "Downtown, City Center",
    latitude: 12.9717,
    longitude: 77.5947,
    size: "200 sq m",
    playerCount: 20,
    courtType: "Indoor, Wooden Flooring",
    bookingCharge: 300,
    lighting: "Yes, Natural & LED",
    photos: ["https://example.com/photos/yoga1.jpg"],
    amenities: ["Changing Rooms", "Showers", "Parking", "Meditation Area"],
    equipmentAvailable: ["Yoga Mats", "Blocks", "Straps"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Peaceful environment!", "Excellent instructors."],
    owner: { name: "John Carter", phone: "1234567892", email: "johnyoga@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Yoga Studio",
    sportType: "Yoga",
    location: "Central Park",
    latitude: 12.9782,
    longitude: 77.5972,
    size: "180 sq m",
    playerCount: 15,
    courtType: "Indoor, Wooden Flooring",
    bookingCharge: 250,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/yoga2.jpg"],
    amenities: ["Parking", "Meditation Area", "Changing Rooms"],
    equipmentAvailable: ["Yoga Mats", "Blocks", "Straps", "Bolsters"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
    ],
    rating: 4.5,
    reviews: ["Great location and ambiance.", "Friendly instructors."],
    owner: { name: "Alice Green", phone: "9876543212", email: "aliceyoga@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Yoga Retreat",
    sportType: "Yoga",
    location: "Eastside District",
    latitude: 12.9807,
    longitude: 77.6012,
    size: "220 sq m",
    playerCount: 25,
    courtType: "Indoor, Wooden Flooring",
    bookingCharge: 350,
    lighting: "Yes, LED & Natural",
    photos: ["https://example.com/photos/yoga3.jpg"],
    amenities: ["Parking", "Changing Rooms", "Meditation Area", "Cafeteria"],
    equipmentAvailable: ["Yoga Mats", "Blocks", "Straps", "Bolsters", "Yoga Wheels"],
    slots: [
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.8,
    reviews: ["Amazing retreat feel!", "Professional classes."],
    owner: { name: "Mark Taylor", phone: "9988776652", email: "markyoga@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Westside Yoga Academy",
    sportType: "Yoga",
    location: "Westside",
    latitude: 12.9652,
    longitude: 77.5902,
    size: "200 sq m",
    playerCount: 20,
    courtType: "Indoor, Wooden Flooring",
    bookingCharge: 280,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/yoga4.jpg"],
    amenities: ["Parking", "Changing Rooms", "Meditation Area"],
    equipmentAvailable: ["Yoga Mats", "Blocks", "Straps"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: true },
      { time: "14:00-15:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Well-maintained studio.", "Calming atmosphere."],
    owner: { name: "Sophie Lee", phone: "1122445562", email: "sophyyoga@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Yoga Hub",
    sportType: "Yoga",
    location: "Uptown",
    latitude: 12.9902,
    longitude: 77.6052,
    size: "210 sq m",
    playerCount: 25,
    courtType: "Indoor, Wooden Flooring",
    bookingCharge: 320,
    lighting: "Yes, LED & Natural",
    photos: ["https://example.com/photos/yoga5.jpg"],
    amenities: ["Locker Rooms", "Parking", "Meditation Area", "Cafeteria"],
    equipmentAvailable: ["Yoga Mats", "Blocks", "Straps", "Bolsters", "Yoga Wheels"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
    ],
    rating: 4.9,
    reviews: ["Excellent instructors!", "Love the calm ambiance."],
    owner: { name: "Emma Brown", phone: "5566778892", email: "emmayoga@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Gym -------------------
const gyms = [
  {
    name: "Downtown Fitness Center",
    sportType: "Gym",
    location: "Downtown, City Center",
    latitude: 12.9718,
    longitude: 77.5948,
    size: "500 sq m",
    playerCount: 30,
    courtType: "Indoor, Modern Equipment",
    bookingCharge: 400,
    lighting: "Yes, LED & Natural",
    photos: ["https://example.com/photos/gym1.jpg"],
    amenities: ["Locker Rooms", "Shower", "Parking", "Sauna"],
    equipmentAvailable: ["Treadmills", "Weights", "Ellipticals", "Bikes"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Top-notch equipment!", "Friendly staff."],
    owner: { name: "John Carter", phone: "1234567893", email: "johnfitness@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Gym Hub",
    sportType: "Gym",
    location: "Central Park",
    latitude: 12.9783,
    longitude: 77.5973,
    size: "450 sq m",
    playerCount: 25,
    courtType: "Indoor, Modern Equipment",
    bookingCharge: 350,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/gym2.jpg"],
    amenities: ["Locker Rooms", "Parking", "Sauna"],
    equipmentAvailable: ["Treadmills", "Weights", "Ellipticals"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
    ],
    rating: 4.5,
    reviews: ["Well-maintained gym.", "Good atmosphere."],
    owner: { name: "Alice Green", phone: "9876543213", email: "alicefitness@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Strength & Conditioning",
    sportType: "Gym",
    location: "Eastside District",
    latitude: 12.9808,
    longitude: 77.6013,
    size: "550 sq m",
    playerCount: 35,
    courtType: "Indoor, Modern Equipment",
    bookingCharge: 450,
    lighting: "Yes, LED & Natural",
    photos: ["https://example.com/photos/gym3.jpg"],
    amenities: ["Locker Rooms", "Shower", "Parking", "Sauna", "Protein Bar"],
    equipmentAvailable: ["Treadmills", "Weights", "Ellipticals", "Bikes", "Resistance Bands"],
    slots: [
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.8,
    reviews: ["Excellent facilities!", "Highly recommended."],
    owner: { name: "Mark Taylor", phone: "9988776653", email: "markgym@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Westside Bodybuilding Gym",
    sportType: "Gym",
    location: "Westside",
    latitude: 12.9653,
    longitude: 77.5903,
    size: "480 sq m",
    playerCount: 28,
    courtType: "Indoor, Modern Equipment",
    bookingCharge: 380,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/gym4.jpg"],
    amenities: ["Locker Rooms", "Parking", "Shower"],
    equipmentAvailable: ["Treadmills", "Weights", "Ellipticals", "Bikes"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: true },
      { time: "14:00-15:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Professional gym.", "Friendly trainers."],
    owner: { name: "Sophie Lee", phone: "1122445563", email: "sophiegym@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Health Club",
    sportType: "Gym",
    location: "Uptown",
    latitude: 12.9903,
    longitude: 77.6053,
    size: "520 sq m",
    playerCount: 32,
    courtType: "Indoor, Modern Equipment",
    bookingCharge: 420,
    lighting: "Yes, LED & Natural",
    photos: ["https://example.com/photos/gym5.jpg"],
    amenities: ["Locker Rooms", "Parking", "Shower", "Sauna", "Protein Bar"],
    equipmentAvailable: ["Treadmills", "Weights", "Ellipticals", "Bikes", "Resistance Bands"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
    ],
    rating: 4.9,
    reviews: ["Best gym experience!", "Loved the trainers."],
    owner: { name: "Emma Brown", phone: "5566778893", email: "emmagym@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Table Tennis -------------------
const tableTennisCourts = [
  {
    name: "Downtown Ping Pong Arena",
    sportType: "Table Tennis",
    location: "Downtown, City Center",
    latitude: 12.9719,
    longitude: 77.5949,
    size: "10x5 m",
    playerCount: 2,
    courtType: "Indoor, Professional Tables",
    bookingCharge: 150,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tt1.jpg"],
    amenities: ["Seating", "Locker Rooms", "Parking"],
    equipmentAvailable: ["Paddles", "Balls", "Scoreboard"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Great tables!", "Well-maintained area."],
    owner: { name: "John Carter", phone: "1234567801", email: "john.tt@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Table Tennis Club",
    sportType: "Table Tennis",
    location: "Central Park",
    latitude: 12.9784,
    longitude: 77.5974,
    size: "12x6 m",
    playerCount: 4,
    courtType: "Indoor, Professional Tables",
    bookingCharge: 160,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tt2.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Paddles", "Balls"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
    ],
    rating: 4.5,
    reviews: ["Perfect for doubles.", "Friendly staff."],
    owner: { name: "Alice Green", phone: "9876543201", email: "alice.tt@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Table Tennis Hall",
    sportType: "Table Tennis",
    location: "Eastside District",
    latitude: 12.9809,
    longitude: 77.6014,
    size: "10x5 m",
    playerCount: 2,
    courtType: "Indoor, Professional Tables",
    bookingCharge: 155,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tt3.jpg"],
    amenities: ["Seating", "Locker Rooms", "Parking", "Water Dispensers"],
    equipmentAvailable: ["Paddles", "Balls", "Scoreboard"],
    slots: [
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Excellent tables!", "Professional setup."],
    owner: { name: "Mark Taylor", phone: "9988776801", email: "mark.tt@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Westside Table Tennis Arena",
    sportType: "Table Tennis",
    location: "Westside",
    latitude: 12.9654,
    longitude: 77.5904,
    size: "10x5 m",
    playerCount: 2,
    courtType: "Indoor, Professional Tables",
    bookingCharge: 150,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tt4.jpg"],
    amenities: ["Seating", "Parking", "Water Dispensers"],
    equipmentAvailable: ["Paddles", "Balls"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: true },
      { time: "14:00-15:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Well-kept hall.", "Good location."],
    owner: { name: "Sophie Lee", phone: "1122446801", email: "sophie.tt@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Table Tennis Club",
    sportType: "Table Tennis",
    location: "Uptown",
    latitude: 12.9904,
    longitude: 77.6054,
    size: "12x6 m",
    playerCount: 4,
    courtType: "Indoor, Professional Tables",
    bookingCharge: 165,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/tt5.jpg"],
    amenities: ["Seating", "Locker Rooms", "Parking", "Water Dispensers"],
    equipmentAvailable: ["Paddles", "Balls", "Scoreboard"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Professional setup!", "Loved playing here."],
    owner: { name: "Emma Brown", phone: "5566776801", email: "emma.tt@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Hockey -------------------
const hockeyFields = [
  {
    name: "Downtown Hockey Field",
    sportType: "Hockey",
    location: "Downtown, City Center",
    latitude: 12.9712,
    longitude: 77.5945,
    size: "91.4x55 m",
    playerCount: 11,
    courtType: "Outdoor, Turf",
    bookingCharge: 600,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/hockey1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Sticks", "Balls", "Goalposts"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Great field!", "Well-maintained turf."],
    owner: { name: "John Carter", phone: "1234567891", email: "john.hockey@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Hockey Arena",
    sportType: "Hockey",
    location: "Central Park",
    latitude: 12.9785,
    longitude: 77.5975,
    size: "91.4x55 m",
    playerCount: 11,
    courtType: "Indoor, Synthetic",
    bookingCharge: 650,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/hockey2.jpg"],
    amenities: ["Seating", "Parking", "Locker Rooms"],
    equipmentAvailable: ["Sticks", "Balls", "Goalposts"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
    ],
    rating: 4.7,
    reviews: ["Perfect for tournaments.", "Good indoor facility."],
    owner: { name: "Alice Green", phone: "9876543211", email: "alice.hockey@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Eastside Hockey Ground",
    sportType: "Hockey",
    location: "Eastside District",
    latitude: 12.9810,
    longitude: 77.6015,
    size: "91.4x55 m",
    playerCount: 11,
    courtType: "Outdoor, Turf",
    bookingCharge: 620,
    lighting: "Yes, Floodlights",
    photos: ["https://example.com/photos/hockey3.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating", "Water Dispensers"],
    equipmentAvailable: ["Sticks", "Balls", "Goalposts"],
    slots: [
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.8,
    reviews: ["Excellent turf!", "Very spacious."],
    owner: { name: "Mark Taylor", phone: "9988776651", email: "mark.hockey@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Westside Hockey Field",
    sportType: "Hockey",
    location: "Westside",
    latitude: 12.9655,
    longitude: 77.5905,
    size: "91.4x55 m",
    playerCount: 11,
    courtType: "Outdoor, Synthetic",
    bookingCharge: 610,
    lighting: "No",
    photos: ["https://example.com/photos/hockey4.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Sticks", "Balls"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: true },
      { time: "14:00-15:00", isBooked: false },
    ],
    rating: 4.5,
    reviews: ["Good location.", "Well-maintained."],
    owner: { name: "Sophie Lee", phone: "1122445561", email: "sophie.hockey@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Hockey Arena",
    sportType: "Hockey",
    location: "Uptown",
    latitude: 12.9905,
    longitude: 77.6055,
    size: "91.4x55 m",
    playerCount: 11,
    courtType: "Indoor, Turf",
    bookingCharge: 670,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/hockey5.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Sticks", "Balls", "Goalposts"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
    ],
    rating: 4.9,
    reviews: ["Professional setup!", "Perfect for practice."],
    owner: { name: "Emma Brown", phone: "5566778891", email: "emma.hockey@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Cycling -------------------
const cyclingTracks = [
  {
    name: "Downtown Cycling Track",
    sportType: "Cycling",
    location: "Downtown, City Center",
    latitude: 12.9710,
    longitude: 77.5940,
    size: "5 km loop",
    playerCount: 20,
    courtType: "Outdoor, Asphalt",
    bookingCharge: 200,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/cycling1.jpg"],
    amenities: ["Parking", "Water Stations", "Seating"],
    equipmentAvailable: ["Bicycles", "Helmets", "Locks"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.5,
    reviews: ["Great track!", "Smooth surface."],
    owner: { name: "John Carter", phone: "1234567892", email: "john.cycling@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Cycling Arena",
    sportType: "Cycling",
    location: "Central Park",
    latitude: 12.9785,
    longitude: 77.5965,
    size: "4 km loop",
    playerCount: 15,
    courtType: "Outdoor, Concrete",
    bookingCharge: 180,
    lighting: "No",
    photos: ["https://example.com/photos/cycling2.jpg"],
    amenities: ["Seating", "Parking"],
    equipmentAvailable: ["Bicycles", "Helmets"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
    ],
    rating: 4.4,
    reviews: ["Nice track for beginners.", "Well-marked paths."],
    owner: { name: "Alice Green", phone: "9876543212", email: "alice.cycling@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Cycling Park",
    sportType: "Cycling",
    location: "Eastside District",
    latitude: 12.9815,
    longitude: 77.6010,
    size: "6 km loop",
    playerCount: 25,
    courtType: "Outdoor, Asphalt",
    bookingCharge: 220,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/cycling3.jpg"],
    amenities: ["Parking", "Water Stations", "Seating", "First Aid"],
    equipmentAvailable: ["Bicycles", "Helmets", "Locks"],
    slots: [
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Excellent track!", "Good for long rides."],
    owner: { name: "Mark Taylor", phone: "9988776652", email: "mark.cycling@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Westside Cycling Track",
    sportType: "Cycling",
    location: "Westside",
    latitude: 12.9655,
    longitude: 77.5905,
    size: "3 km loop",
    playerCount: 10,
    courtType: "Outdoor, Concrete",
    bookingCharge: 150,
    lighting: "No",
    photos: ["https://example.com/photos/cycling4.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Bicycles", "Helmets"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: true },
      { time: "14:00-15:00", isBooked: false },
    ],
    rating: 4.3,
    reviews: ["Good track for kids.", "Safe and clean."],
    owner: { name: "Sophie Lee", phone: "1122445562", email: "sophie.cycling@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Cycling Arena",
    sportType: "Cycling",
    location: "Uptown",
    latitude: 12.9910,
    longitude: 77.6055,
    size: "7 km loop",
    playerCount: 30,
    courtType: "Outdoor, Asphalt",
    bookingCharge: 250,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/cycling5.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating", "Water Stations"],
    equipmentAvailable: ["Bicycles", "Helmets", "Locks"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Professional track!", "Great for training."],
    owner: { name: "Emma Brown", phone: "5566778892", email: "emma.cycling@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Skating -------------------
const skatingRinks = [
  {
    name: "Downtown Skating Rink",
    sportType: "Skating",
    location: "Downtown, City Center",
    latitude: 12.9715,
    longitude: 77.5945,
    size: "60x30 m",
    playerCount: 20,
    courtType: "Indoor, Wooden",
    bookingCharge: 300,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/skating1.jpg"],
    amenities: ["Parking", "Changing Rooms", "Seating"],
    equipmentAvailable: ["Skates", "Helmets", "Pads"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Great indoor rink!", "Perfect for beginners."],
    owner: { name: "John Carter", phone: "1234567893", email: "john.skating@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Skating Arena",
    sportType: "Skating",
    location: "Central Park",
    latitude: 12.9785,
    longitude: 77.5975,
    size: "70x35 m",
    playerCount: 25,
    courtType: "Outdoor, Concrete",
    bookingCharge: 280,
    lighting: "No",
    photos: ["https://example.com/photos/skating2.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Skates", "Helmets"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
    ],
    rating: 4.4,
    reviews: ["Good outdoor rink.", "Safe and clean."],
    owner: { name: "Alice Green", phone: "9876543213", email: "alice.skating@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Skating Park",
    sportType: "Skating",
    location: "Eastside District",
    latitude: 12.9810,
    longitude: 77.6005,
    size: "65x32 m",
    playerCount: 20,
    courtType: "Indoor, Synthetic",
    bookingCharge: 320,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/skating3.jpg"],
    amenities: ["Parking", "Water Stations", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Skates", "Helmets", "Pads"],
    slots: [
      { time: "08:00-09:00", isBooked: true },
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Excellent rink!", "Perfect surface for skating."],
    owner: { name: "Mark Taylor", phone: "9988776653", email: "mark.skating@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Westside Skating Track",
    sportType: "Skating",
    location: "Westside",
    latitude: 12.9655,
    longitude: 77.5910,
    size: "50x25 m",
    playerCount: 15,
    courtType: "Outdoor, Concrete",
    bookingCharge: 250,
    lighting: "No",
    photos: ["https://example.com/photos/skating4.jpg"],
    amenities: ["Parking", "Seating"],
    equipmentAvailable: ["Skates", "Helmets"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: true },
      { time: "14:00-15:00", isBooked: false },
    ],
    rating: 4.3,
    reviews: ["Good for casual skating.", "Safe and spacious."],
    owner: { name: "Sophie Lee", phone: "1122445563", email: "sophie.skating@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Skating Arena",
    sportType: "Skating",
    location: "Uptown",
    latitude: 12.9905,
    longitude: 77.6055,
    size: "75x40 m",
    playerCount: 30,
    courtType: "Indoor, Wooden",
    bookingCharge: 350,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/skating5.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating", "Water Stations"],
    equipmentAvailable: ["Skates", "Helmets", "Pads"],
    slots: [
      { time: "15:00-16:00", isBooked: false },
      { time: "16:00-17:00", isBooked: false },
      { time: "17:00-18:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Professional rink!", "Loved the smooth surface."],
    owner: { name: "Emma Brown", phone: "5566778893", email: "emma.skating@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Golf -------------------
const golfCourses = [
  {
    name: "Downtown Golf Club",
    sportType: "Golf",
    location: "Downtown, City Center",
    latitude: 12.9710,
    longitude: 77.5940,
    size: "18 Holes",
    playerCount: 4,
    courtType: "Outdoor, Grass",
    bookingCharge: 1500,
    lighting: "No",
    photos: ["https://example.com/photos/golf1.jpg"],
    amenities: ["Club House", "Parking", "Seating", "Pro Shop"],
    equipmentAvailable: ["Golf Clubs", "Golf Balls", "Trolleys"],
    slots: [
      { time: "06:00-09:00", isBooked: false },
      { time: "09:00-12:00", isBooked: true },
      { time: "12:00-15:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Beautiful course!", "Excellent greens."],
    owner: { name: "John Carter", phone: "1234567894", email: "john.golf@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Central Park Golf Course",
    sportType: "Golf",
    location: "Central Park",
    latitude: 12.9785,
    longitude: 77.5975,
    size: "9 Holes",
    playerCount: 4,
    courtType: "Outdoor, Grass",
    bookingCharge: 1200,
    lighting: "No",
    photos: ["https://example.com/photos/golf2.jpg"],
    amenities: ["Parking", "Seating", "Pro Shop"],
    equipmentAvailable: ["Golf Clubs", "Golf Balls"],
    slots: [
      { time: "07:00-10:00", isBooked: true },
      { time: "10:00-13:00", isBooked: false },
      { time: "13:00-16:00", isBooked: false },
    ],
    rating: 4.5,
    reviews: ["Great 9-hole course.", "Friendly staff."],
    owner: { name: "Alice Green", phone: "9876543214", email: "alice.golf@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Eastside Golf Club",
    sportType: "Golf",
    location: "Eastside District",
    latitude: 12.9815,
    longitude: 77.6000,
    size: "18 Holes",
    playerCount: 4,
    courtType: "Outdoor, Grass",
    bookingCharge: 1600,
    lighting: "No",
    photos: ["https://example.com/photos/golf3.jpg"],
    amenities: ["Club House", "Parking", "Seating", "Cafeteria"],
    equipmentAvailable: ["Golf Clubs", "Balls", "Trolleys"],
    slots: [
      { time: "06:00-09:00", isBooked: false },
      { time: "09:00-12:00", isBooked: false },
      { time: "12:00-15:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Perfect course for tournaments.", "Well-maintained greens."],
    owner: { name: "Mark Taylor", phone: "9988776654", email: "mark.golf@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Westside Golf Resort",
    sportType: "Golf",
    location: "Westside",
    latitude: 12.9655,
    longitude: 77.5915,
    size: "9 Holes",
    playerCount: 4,
    courtType: "Outdoor, Grass",
    bookingCharge: 1300,
    lighting: "No",
    photos: ["https://example.com/photos/golf4.jpg"],
    amenities: ["Parking", "Club House", "Seating"],
    equipmentAvailable: ["Golf Clubs", "Balls"],
    slots: [
      { time: "08:00-11:00", isBooked: false },
      { time: "11:00-14:00", isBooked: true },
      { time: "14:00-17:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Nice short course.", "Good for practice rounds."],
    owner: { name: "Sophie Lee", phone: "1122445564", email: "sophie.golf@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Uptown Golf Arena",
    sportType: "Golf",
    location: "Uptown",
    latitude: 12.9905,
    longitude: 77.6055,
    size: "18 Holes",
    playerCount: 4,
    courtType: "Outdoor, Grass",
    bookingCharge: 1700,
    lighting: "No",
    photos: ["https://example.com/photos/golf5.jpg"],
    amenities: ["Club House", "Parking", "Seating", "Pro Shop", "Cafeteria"],
    equipmentAvailable: ["Golf Clubs", "Balls", "Trolleys"],
    slots: [
      { time: "06:00-09:00", isBooked: true },
      { time: "09:00-12:00", isBooked: false },
      { time: "12:00-15:00", isBooked: false },
    ],
    rating: 4.9,
    reviews: ["Top-notch facilities!", "Fantastic course layout."],
    owner: { name: "Emma Brown", phone: "5566778894", email: "emma.golf@example.com" },
    maxBookingHours: 3,
  },
];

// ------------------- Martial Arts -------------------
const martialArtsDojo = [
  {
    name: "Downtown Karate Dojo",
    sportType: "Martial Arts",
    location: "Downtown, City Center",
    latitude: 12.9712,
    longitude: 77.5942,
    size: "200 sqm",
    playerCount: 20,
    courtType: "Indoor, Mats",
    bookingCharge: 400,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/karate1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating"],
    equipmentAvailable: ["Mats", "Punching Bags", "Gloves"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Great instructors!", "Well-maintained dojo."],
    owner: { name: "John Carter", phone: "1234567801", email: "john.martial@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Taekwondo Center",
    sportType: "Martial Arts",
    location: "Central Park",
    latitude: 12.9782,
    longitude: 77.5972,
    size: "180 sqm",
    playerCount: 15,
    courtType: "Indoor, Mats",
    bookingCharge: 450,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/taekwondo1.jpg"],
    amenities: ["Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Mats", "Pads", "Gloves"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: true },
      { time: "11:00-12:00", isBooked: false },
    ],
    rating: 4.5,
    reviews: ["Excellent training!", "Friendly coaches."],
    owner: { name: "Alice Green", phone: "9876543211", email: "alice.martial@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Judo Academy",
    sportType: "Martial Arts",
    location: "Eastside District",
    latitude: 12.9817,
    longitude: 77.6002,
    size: "220 sqm",
    playerCount: 25,
    courtType: "Indoor, Mats",
    bookingCharge: 500,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/judo1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating", "Showers"],
    equipmentAvailable: ["Mats", "Judo Belts", "Gloves"],
    slots: [
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false },
      { time: "09:00-10:00", isBooked: false },
    ],
    rating: 4.8,
    reviews: ["Professional instructors.", "Spacious training area."],
    owner: { name: "Mark Taylor", phone: "9988776611", email: "mark.martial@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Westside Mixed Martial Arts Gym",
    sportType: "Martial Arts",
    location: "Westside",
    latitude: 12.9657,
    longitude: 77.5917,
    size: "250 sqm",
    playerCount: 30,
    courtType: "Indoor, Mats",
    bookingCharge: 550,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/mma1.jpg"],
    amenities: ["Parking", "Seating", "Locker Rooms", "Showers"],
    equipmentAvailable: ["Mats", "Pads", "Gloves", "Bags"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false },
    ],
    rating: 4.9,
    reviews: ["Best MMA training in town!", "Highly recommended."],
    owner: { name: "Sophie Lee", phone: "1122446611", email: "sophie.martial@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Uptown Kung Fu Academy",
    sportType: "Martial Arts",
    location: "Uptown",
    latitude: 12.9907,
    longitude: 77.6057,
    size: "200 sqm",
    playerCount: 20,
    courtType: "Indoor, Mats",
    bookingCharge: 480,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/kungfu1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Seating", "Showers"],
    equipmentAvailable: ["Mats", "Gloves", "Training Weapons"],
    slots: [
      { time: "14:00-15:00", isBooked: false },
      { time: "15:00-16:00", isBooked: true },
      { time: "16:00-17:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Authentic Kung Fu training!", "Skilled instructors."],
    owner: { name: "Emma Brown", phone: "5566776611", email: "emma.martial@example.com" },
    maxBookingHours: 2,
  },
];

// ------------------- Archery -------------------
const archeryRanges = [
  {
    name: "Downtown Archery Range",
    sportType: "Archery",
    location: "Downtown, City Center",
    latitude: 12.9715,
    longitude: 77.5945,
    size: "100x50 m",
    playerCount: 10,
    courtType: "Outdoor",
    bookingCharge: 350,
    lighting: "No",
    photos: ["https://example.com/photos/archery1.jpg"],
    amenities: ["Parking", "Seating", "Changing Rooms"],
    equipmentAvailable: ["Bows", "Arrows", "Targets"],
    slots: [
      { time: "08:00-09:00", isBooked: false },
      { time: "09:00-10:00", isBooked: true },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.5,
    reviews: ["Perfect for beginners!", "Well-maintained targets."],
    owner: { name: "John Archer", phone: "1234567812", email: "john.archery@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Archery Club",
    sportType: "Archery",
    location: "Central Park",
    latitude: 12.9785,
    longitude: 77.5975,
    size: "120x60 m",
    playerCount: 12,
    courtType: "Outdoor",
    bookingCharge: 400,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/archery2.jpg"],
    amenities: ["Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Bows", "Arrows", "Targets", "Quivers"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: false },
      { time: "12:00-13:00", isBooked: true },
    ],
    rating: 4.7,
    reviews: ["Professional training available!", "Friendly staff."],
    owner: { name: "Alice Bowman", phone: "9876543221", email: "alice.archery@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Eastside Archery Arena",
    sportType: "Archery",
    location: "Eastside District",
    latitude: 12.9810,
    longitude: 77.6000,
    size: "110x55 m",
    playerCount: 15,
    courtType: "Outdoor",
    bookingCharge: 420,
    lighting: "No",
    photos: ["https://example.com/photos/archery3.jpg"],
    amenities: ["Parking", "Seating", "Changing Rooms"],
    equipmentAvailable: ["Bows", "Arrows", "Targets"],
    slots: [
      { time: "06:00-07:00", isBooked: true },
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Great place for practice.", "Well-maintained lanes."],
    owner: { name: "Mark Arrow", phone: "9988776622", email: "mark.archery@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Westside Archery Center",
    sportType: "Archery",
    location: "Westside",
    latitude: 12.9655,
    longitude: 77.5915,
    size: "120x60 m",
    playerCount: 12,
    courtType: "Outdoor",
    bookingCharge: 390,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/archery4.jpg"],
    amenities: ["Parking", "Seating", "Locker Rooms"],
    equipmentAvailable: ["Bows", "Arrows", "Targets"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false },
    ],
    rating: 4.8,
    reviews: ["Excellent coaching!", "Spacious and safe."],
    owner: { name: "Sophie Archer", phone: "1122446622", email: "sophie.archery@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Uptown Archery Grounds",
    sportType: "Archery",
    location: "Uptown",
    latitude: 12.9910,
    longitude: 77.6050,
    size: "100x50 m",
    playerCount: 10,
    courtType: "Outdoor",
    bookingCharge: 400,
    lighting: "No",
    photos: ["https://example.com/photos/archery5.jpg"],
    amenities: ["Parking", "Seating", "Changing Rooms"],
    equipmentAvailable: ["Bows", "Arrows", "Targets", "Quivers"],
    slots: [
      { time: "14:00-15:00", isBooked: false },
      { time: "15:00-16:00", isBooked: true },
      { time: "16:00-17:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Very professional staff.", "Clean and safe range."],
    owner: { name: "Emma Bow", phone: "5566776622", email: "emma.archery@example.com" },
    maxBookingHours: 2,
  },
];

// ------------------- Rock Climbing -------------------
const rockClimbingSpots = [
  {
    name: "Downtown Climbing Gym",
    sportType: "Rock Climbing",
    location: "Downtown, City Center",
    latitude: 12.9717,
    longitude: 77.5947,
    size: "Indoor, 15m walls",
    playerCount: 5,
    courtType: "Indoor, Bouldering & Ropes",
    bookingCharge: 600,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/climbing1.jpg"],
    amenities: ["Changing Rooms", "Locker Rooms", "Parking"],
    equipmentAvailable: ["Harnesses", "Ropes", "Shoes", "Helmets"],
    slots: [
      { time: "08:00-09:00", isBooked: false },
      { time: "09:00-10:00", isBooked: true },
      { time: "10:00-11:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Perfect for beginners!", "Great instructors."],
    owner: { name: "John Rock", phone: "1234567891", email: "john.climb@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Climbing Arena",
    sportType: "Rock Climbing",
    location: "Central Park",
    latitude: 12.9782,
    longitude: 77.5965,
    size: "Indoor, 20m walls",
    playerCount: 6,
    courtType: "Indoor, Lead Climbing",
    bookingCharge: 650,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/climbing2.jpg"],
    amenities: ["Parking", "Locker Rooms", "Seating"],
    equipmentAvailable: ["Harnesses", "Ropes", "Shoes", "Helmets", "Chalk"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: false },
      { time: "12:00-13:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Very professional gym!", "Great safety measures."],
    owner: { name: "Alice Boulder", phone: "9876543211", email: "alice.climb@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Eastside Climbing Walls",
    sportType: "Rock Climbing",
    location: "Eastside District",
    latitude: 12.9812,
    longitude: 77.6005,
    size: "Indoor, 18m walls",
    playerCount: 5,
    courtType: "Indoor, Bouldering",
    bookingCharge: 620,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/climbing3.jpg"],
    amenities: ["Parking", "Changing Rooms", "Seating"],
    equipmentAvailable: ["Harnesses", "Ropes", "Shoes", "Chalk"],
    slots: [
      { time: "06:00-07:00", isBooked: true },
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Friendly instructors!", "Great practice walls."],
    owner: { name: "Mark Climb", phone: "9988776611", email: "mark.climb@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Westside Climbing Hub",
    sportType: "Rock Climbing",
    location: "Westside",
    latitude: 12.9657,
    longitude: 77.5917,
    size: "Indoor & Outdoor, 22m walls",
    playerCount: 8,
    courtType: "Indoor Lead & Outdoor Top Rope",
    bookingCharge: 700,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/climbing4.jpg"],
    amenities: ["Parking", "Locker Rooms", "Seating"],
    equipmentAvailable: ["Harnesses", "Ropes", "Shoes", "Helmets", "Belay Devices"],
    slots: [
      { time: "10:00-11:00", isBooked: false },
      { time: "11:00-12:00", isBooked: true },
      { time: "12:00-13:00", isBooked: false },
    ],
    rating: 4.9,
    reviews: ["Professional gym!", "Loved the outdoor setup."],
    owner: { name: "Sophie Cliff", phone: "1122446611", email: "sophie.climb@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Uptown Climbing Grounds",
    sportType: "Rock Climbing",
    location: "Uptown",
    latitude: 12.9915,
    longitude: 77.6055,
    size: "Indoor, 20m walls",
    playerCount: 6,
    courtType: "Indoor, Bouldering & Lead",
    bookingCharge: 680,
    lighting: "Yes, LED",
    photos: ["https://example.com/photos/climbing5.jpg"],
    amenities: ["Parking", "Changing Rooms", "Locker Rooms", "Seating"],
    equipmentAvailable: ["Harnesses", "Ropes", "Shoes", "Helmets", "Chalk"],
    slots: [
      { time: "14:00-15:00", isBooked: false },
      { time: "15:00-16:00", isBooked: true },
      { time: "16:00-17:00", isBooked: false },
    ],
    rating: 4.8,
    reviews: ["Great training environment!", "Friendly staff."],
    owner: { name: "Emma Cliff", phone: "5566776611", email: "emma.climb@example.com" },
    maxBookingHours: 2,
  },
];

// ------------------- Surfing -------------------
const surfingSpots = [
  {
    name: "Sunrise Surf Beach",
    sportType: "Surfing",
    location: "North Coast",
    latitude: 12.9710,
    longitude: 77.5930,
    size: "Beach, 500m stretch",
    playerCount: 6,
    courtType: "Open Water",
    bookingCharge: 800,
    lighting: "No",
    photos: ["https://example.com/photos/surf1.jpg"],
    amenities: ["Changing Rooms", "Parking", "Shower"],
    equipmentAvailable: ["Surfboards", "Wetsuits", "Leashes"],
    slots: [
      { time: "06:00-07:00", isBooked: false },
      { time: "07:00-08:00", isBooked: true },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.7,
    reviews: ["Perfect waves!", "Great instructors."],
    owner: { name: "John Wave", phone: "1234567801", email: "john.surf@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Central Surf Point",
    sportType: "Surfing",
    location: "Central Beach",
    latitude: 12.9785,
    longitude: 77.5962,
    size: "Beach, 600m stretch",
    playerCount: 8,
    courtType: "Open Water",
    bookingCharge: 850,
    lighting: "No",
    photos: ["https://example.com/photos/surf2.jpg"],
    amenities: ["Parking", "Shower", "Cafe"],
    equipmentAvailable: ["Surfboards", "Wetsuits", "Leashes", "Life Jackets"],
    slots: [
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: false },
      { time: "09:00-10:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Amazing waves!", "Safe and fun."],
    owner: { name: "Alice Wave", phone: "9876543201", email: "alice.surf@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Eastside Surf Club",
    sportType: "Surfing",
    location: "East Coast",
    latitude: 12.9820,
    longitude: 77.6000,
    size: "Beach, 400m stretch",
    playerCount: 5,
    courtType: "Open Water",
    bookingCharge: 780,
    lighting: "No",
    photos: ["https://example.com/photos/surf3.jpg"],
    amenities: ["Changing Rooms", "Parking", "Shower"],
    equipmentAvailable: ["Surfboards", "Wetsuits", "Leashes"],
    slots: [
      { time: "06:00-07:00", isBooked: true },
      { time: "07:00-08:00", isBooked: false },
      { time: "08:00-09:00", isBooked: false },
    ],
    rating: 4.6,
    reviews: ["Good waves for beginners!", "Friendly staff."],
    owner: { name: "Mark Surf", phone: "9988776601", email: "mark.surf@example.com" },
    maxBookingHours: 2,
  },
  {
    name: "Westside Surf Arena",
    sportType: "Surfing",
    location: "West Coast",
    latitude: 12.9655,
    longitude: 77.5905,
    size: "Beach, 550m stretch",
    playerCount: 7,
    courtType: "Open Water",
    bookingCharge: 820,
    lighting: "No",
    photos: ["https://example.com/photos/surf4.jpg"],
    amenities: ["Parking", "Shower", "Cafe"],
    equipmentAvailable: ["Surfboards", "Wetsuits", "Leashes", "Life Jackets"],
    slots: [
      { time: "09:00-10:00", isBooked: false },
      { time: "10:00-11:00", isBooked: true },
      { time: "11:00-12:00", isBooked: false },
    ],
    rating: 4.9,
    reviews: ["Professional instructors!", "Perfect for advanced surfers."],
    owner: { name: "Sophie Wave", phone: "1122446601", email: "sophie.surf@example.com" },
    maxBookingHours: 3,
  },
  {
    name: "Uptown Surf Point",
    sportType: "Surfing",
    location: "Uptown Beach",
    latitude: 12.9912,
    longitude: 77.6052,
    size: "Beach, 450m stretch",
    playerCount: 6,
    courtType: "Open Water",
    bookingCharge: 810,
    lighting: "No",
    photos: ["https://example.com/photos/surf5.jpg"],
    amenities: ["Changing Rooms", "Parking", "Shower", "Cafe"],
    equipmentAvailable: ["Surfboards", "Wetsuits", "Leashes", "Life Jackets"],
    slots: [
      { time: "12:00-13:00", isBooked: false },
      { time: "13:00-14:00", isBooked: false },
      { time: "14:00-15:00", isBooked: true },
    ],
    rating: 4.8,
    reviews: ["Great waves!", "Loved the training sessions."],
    owner: { name: "Emma Wave", phone: "5566776601", email: "emma.surf@example.com" },
    maxBookingHours: 2,
  },
];








